microsoft/BotFramework-Emulator

src/client/css/emulator.css, src/client/dialogs/appSettingsDialog.tsx, src/client/reducers.ts, src/server/botFrameworkService.ts, src/server/conversationManager.ts, src/types/serverSettingsTypes.ts
Adds a checkbox that is used to determine whether ngrok should be used for bots served from localhost or not (see discussion in #65). Also logs the behaviour when ngrok is started or the value of the checkbox is changed.
=> Makes behaviour of ngrok for localhost bots configurable

src/client/addressBar/addressBarOperators.ts, src/client/botEmulatorContext.ts, src/client/mainView.tsx, src/server/main.ts
Adds a protocol handler for receiving botemulator:// URLs. Valid URL parameters include:
- endpoint
- appid
- apppassword
- locale
Example:
botemulator://endpoint=localhost:123&appid=abcd&apppassword=qwerty&locale=En-US
=> Adding a botemulator URL protocol handler

src/server/controllers/connector/conversationsController.ts, src/server/versionManager.ts
This change warns users if they are using an SDK version less than 3.5.0 as these versions use an authentication configuration that will no longer work starting in June, 2017.
Bots need to update their SDK version to continue working beyond this date.
=> Detect sdk version and warn if using a version less than 3.5.0

src/client/payments/index.tsx, src/server/main.ts, src/server/reducers/windowStateReducer.ts, src/server/windowManager.ts, src/types/serverSettingsTypes.ts
Added some logic to check if the main window would appear off screen when the window is restored or created. If it would appear off screen, it tries to restore to the display it was last on, otherwise it goes to the nearest monitor to its last position.
Also, added zoom functionality. Ctrl+= zooms in, Ctrl+- zooms out, and Ctrl+0 restores to the default amount. Zoom levels are shared across all windows and is remembered between sessions.
=> Window positioning and zoom functionality

src/server/botFrameworkAuthentication.ts, src/server/conversationManager.ts, src/server/settings.ts
Supporting the new Bot Framework authentication v3.1 and removing authentication endpoints for v3.0 authentication.
See https://aka.ms/botfxv31authchange for more details on the change.
=> Support Bot Framework authentication v3.1

src/client/mainView.tsx
Also added a maxSize for both panes, so you can't inadvertently hide one pane entirely. This can still happen if the window is resized, though.
=> Split panes takes numbers, not strings, as props

package.json
Since the testbot is written in typescript, we need to use ts-node to run it instead of plain old node
=> fix command to run test bot to use ts-node

package.json, src/client/addressBar/addressBar.tsx, src/client/addressBar/addressBarMenu.tsx, src/client/addressBar/addressBarSearch.tsx, src/client/addressBar/addressBarTextBox.tsx, src/client/reducers.ts, src/client/settings.ts, src/server/main.ts
Support added for following hotkeys:
* F5 / Ctrl+R - Refresh the conversation.
* F10 / Alt+F - Open the menu.
* F6 / Ctrl+L - Focus the address bar.
The same applies for Mac using ⌘ instead of Ctrl.
=> Adding support for hotkeys in Emulator (#304)

src/server/main.ts, src/server/windowManager.ts
Fixes #352.
I assume debounce is preferable to throttle in the case of key presses. Also not sure of exact debounce time, I found 100 milliseconds to be work without making it feel too laggy.
Also a fix to the registerHotKeys function so we can specify which windows the hotkey should apply to. Otherwise the zoom shortcuts didn't work in the payments window.
=> Added debounce to hotkey presses.

src/client/mainView.tsx, src/client/settings.ts
Casting the settings as a Number resulted in dropping the percentage split. Numerous users have been confused by the log panel apparently "disappearing", though it is actually just minimized at the bottom of the right panel.
Setting the default values to numbers insures that on a fresh install the split panels are at reasonable positions. Changing the minimum size of the log panel insures two log entries will just be visible, helping existing users who might not realize their log is hidden.
Another thing we should consider doing is designing the draggable dividers so it is more obvious that they can be dragged, or just by increasing the clickable area so the mouse change on mouse over is more obvious.
=> Fix for log panel being minimized by default.

src/client/logView.tsx, tests/package.json, tests/performance/performance.ts
Related to #115 
Added simple spam performance test, which probably can be further improved, and improved the performance of the emulator when there are many entries in the log view by adding update logic to the entries.
In the current production build, after 255 messages it takes approximately 2.5x as long to send and receive a message from a bot than it does with a new session.  With the new code in this PR, the time stays approximately the same regardless of how many messages have been sent.
=> Added performance test, improved performance of log view with many messages

src/client/addressBar/addressBarBotCreds.tsx, src/client/mainView.tsx, src/types/serverSettingsTypes.ts
- Bug was due to `locale` input field setting value based on an OR operator
- so anytime the field reached an empty state, the left side of the OR operator would evaluate to `false` and default to the app's locale
- Added `en-US` as the default locale for the `default-bot`
=> Fixed bug #314 - locale field was resetting once empty.

gulpfile.js, package-lock.json, package.json, src/server/ngrok.ts, tsconfig.json
Every time we change anything under `/src/`, we need to run `gulp build-app` manually. And it is not incremental build so it is slow to develop the Electron "main" side of the app.
* `gulp-tsc` does not support incremental build, moving away
* Moving `/src/` build into `npm run build:electron`, while keeping `gulp build-app` on-par
It is same as what you did before: `npm run build` for clean build, `gulp build-app` for Electron "main" only. But now you can enable incremental build on "main" side.
To build stuff in lightning speed (~4 seconds), run `npm run build:electron -- --watch`. Then run the Electron app. Your "main" side of code will be watching and building incrementally.
> Tips: don't forget `build:electron` or `gulp build-app` will only build the Electron "main" side, you need to …
=> Enable incremental Electron build

client-v2/src/data/action/botActions.js, client-v2/src/data/action/conversationActions.js, client-v2/src/data/action/editorActions.js, client-v2/src/data/reducer/card.js, client-v2/src/data/reducer/conversation.js, client-v2/src/data/reducer/editor.js, client-v2/src/data/store.js, client-v2/src/ui/editor/botChatEditor/chatPanel.js, client-v2/src/ui/editor/botChatEditor/index.js, client-v2/src/ui/editor/botChatEditor/logPanel.js, client-v2/src/ui/editor/cardEditor/cardJsonEditor/index.js, client-v2/src/ui/editor/cardEditor/cardOutput/index.js, client-v2/src/ui/editor/cardEditor/cardPreview/index.js, client-v2/src/ui/editor/cardEditor/index.js, client-v2/src/ui/editor/conversationEditor/editorPanel.js, client-v2/src/ui/editor/conversationEditor/index.js, client-v2/src/ui/editor/conversationEditor/propertiesPanel.js, client-v2/src/ui/editor/index.js, client-v2/src/ui/layout/expandCollapse.js, client-v2/src/ui/shell/explorer/botExplorer.js, client-v2/src/ui/shell/explorer/cardExplorer.js, client-v2/src/ui/shell/explorer/conversationExplorer.js, client-v2/src/ui/shell/mdi/conversationTab.js, client-v2/src/ui/shell/mdi/index.js, client-v2/src/ui/shell/mdi/tabFactory.js, client-v2/src/utils.js
Shakeup on store to support multiple types of documents.
We only have 3 types of document today:
* Bot chat
* Card
* Conversation
To create and open a bot connection. You need to specifically ask the MDI to open the document for you.
```js
const connectAction = BotActions.connect(`http://localhost:4000/`);
this.props.dispatch(connectAction);
this.props.dispatch(EditorActions.open(constants.ContentType_BotChat, connectAction.payload.botId));
```
```js
{
bot: {
bots: {
'bot:1': { url: '…' },
'bot:2': { url: '…' }
}
},
card: {
cards: {
'card:1': { … }
}
},
conversation: {
conversations: { … }
},
editor: {
activeDocumentId: 'bot:1',
documents: [{
contentType: 'application/vnd.microsoft.botstudio.document.botchat',
documentId: 'bot:1'
}, {
contentType: …
```
=> Shakeup the Redux store for MDI

client-v2/package-lock.json, package-lock.json
[NPM 5.6.0](http://blog.npmjs.org/post/167963735925/v560-2017-11-27) introduced "Fully cross-platform package-lock.json".
Updating `package-lock.json` so NPM on different platforms don't fight again each other (on `fsevents`, `7zip-bin-*`).
=> package-lock.json from npm@5.6.0

packages/app/client/src/data/reducer/editor.ts, packages/app/client/src/ui/shell/multiTabs/index.js, packages/app/client/src/ui/shell/multiTabs/tabBar.js, packages/app/client/src/ui/shell/multiTabs/tabBarTab.js
this makes sure that new endpoint tabs are to the right of the currently active tab and that the tab list is scrolled to the right place
=> Clicking on an endpoint should open to the right of the active editor

packages/app/client/src/ui/shell/explorer/transcriptExplorer/transcriptExplorer.tsx
just changing the label for Transcript explorer to match its functionality
=> Rename "File explorer" to "Transcript explorer"

packages/app/main/src/commands.ts
If we can't open a bot, we should put up a message box explaining the error. Because we encounter the error while initializing the commands, the command service is not initialized when we first encounter the error in botHelper loadBotWithRetry().  So I just let that throw and then catch and render the exception in the command for bot:set-active.
=> Show a message box if we fail to open  a bot

packages/app/client/src/ui/editor/appSettingsEditor.tsx, packages/app/client/src/ui/editor/emulator/parts/log.tsx, packages/app/client/src/ui/shell/mdi/appSettingsTab.js, packages/app/client/src/ui/shell/mdi/tabFactory.js, packages/app/main/src/appMenuBuilder.ts
"app settings" becomes "emulator settings".  Bot section has been removed because that functionality is deprecated.
=> Rename "app settings" and remove bot state section

packages/app/client/src/ui/dialogs/botCreationDialog.tsx, packages/app/main/src/commands.ts, packages/app/main/src/utils.ts
- Removed bot path location field
- Changed title to 'New bot configuration'
- Changed endpoint field placeholder text
- Changed 'Save' button to 'Save and connect'
- After hitting 'Save and connect', the user is then prompted with the save .bot file dialog that is filled with a sanitized filename derived from the Bot Name field
=> Changed bot creation dialog to use new flow.

packages/app/main/src/protocolHandler.ts, packages/app/main/src/utils.ts
This can wait until after Build, but I removed the expectation that protocol query string parameters should be base64 encoded.
=> [POST-BUILD] Protocol parameters are no longer expected to be base64 encoded.

packages/emulator/core/src/conversations/middleware/replyToActivity.ts, packages/emulator/core/src/facility/conversation.ts, packages/emulator/core/src/utils/oauthClientEncoder.ts, packages/emulator/core/src/utils/oauthLinkEncoder.ts
The OAuthEncoders assumed that all activities had a conversation and conversation.id property. Silly me they do not.  The V3 Node SDK sends special debug "event activities" that do not have this property so added some protection to not encode if there is no conversation.id.
=> Support for Node SDK Debug events

src/server/controllers/connector/conversationsController.ts, src/shared/oauthLinkEncoder.ts
This is needed to talk back to the emulator and identify
the conversation when using the Node SDK.
=> Setting conversation id on the TokenExchangeState

packages/app/main/package-lock.json, packages/app/main/package.json, packages/app/main/src/utils.ts
- Added Support for different file encodings:
- ascii
- utf-8
- utf-16le & ucs-2
- latin1 & iso-8859-1
- base64
- binary
- hex
*NOTE*: Have tested loading iso-8859-1 `.json` files and utf-16le `.transcript` files. I think it's possible to also read utf-16**be** encoded files as well using `Buffer.swap16()` but I haven't tried it yet.
=> Added support for different Node-supported file encodings.

packages/app/client/src/data/reducer/bot.ts, packages/app/client/src/ui/editor/botSettingsEditor/index.tsx, packages/app/client/src/ui/shell/main.js, packages/app/main/src/data-v2/reducer/bot.ts, packages/app/main/src/protocolHandler.ts, packages/app/shared/src/constants.ts, packages/app/shared/src/index.ts
- When opening a livechat session with a bot via a protocol URI, the user can now go into Bot Settings and save the bot as a new bot config for later use
- Protocol handler mocks a new bot and places it in the client store to be saved
- Bot settings page will detect that it is a mocked bot on save, and prompt the user to choose a path for the `.bot` file
- Removed unused endpoint state from bot settings page
- now uses `state.bot.services`
- Save and Connect now checks for a valid endpoint service before connecting at the end of save action
- Added checks to client and server side bot reducer to prevent falsy entries from being added to `bots.json`
=> Livechat sessions opened via protocol URI can now be saved as a new bot config

packages/app/client/src/ui/shell/main.tsx
Fix for #507 
Can no longer drag the slider until one of the editors becomes completely invisible
=> Added min width of 160px to each of the editors.

src/server/controllers/connector/conversationsController.ts, src/shared/oauthLinkEncoder.ts
This is a change to the V3 emulator to display a warning when the bot sends an OAuthCard and the emulator does not have ngrok configured. This property is required so that the Azure Bot Service token service can return the token to the emulator and bot once the user has signed in.
=> Add a warning error when using OAuthCards without ngrok

packages/app/main/src/commands.ts
Related to #561 
This change will enforce, **on Mac**, that all external links opened in the emulator will be opened in the foreground.
=> On Mac, links should open in the foreground now.

packages/app/client/src/ui/editor/emulator/parts/inspector.tsx, packages/app/client/src/ui/shell/mdi/tab.tsx
Fix for #559 
- Prevents drag and drop events within the inspector panel
- Also fixed broken editor / tab drag and drops that were caused by `mapDispatchToProps` being passed as the first argument into `<Tab />`'s `connect()` function
=> Can no longer drag and drop within the inspector panel

packages/app/client/src/commands.ts, packages/app/client/src/data/action/fileActions.ts, packages/app/client/src/data/reducer/files.ts, packages/app/main/src/botProjectFileWatcher.ts
Fix for #548 
- File watcher now clears the files store on every call to `watch()`
=> File watcher now clears the files store on every call to watch()

README.md
See: https://emulator.botframework.com
=> Remove this option since the link redirects to the github release page

packages/app/client/src/ui/editor/emulator/parts/chat.tsx
Fix #543, add `wc-wide` to the Web Chat so it will make Adaptive Cards looks wider and not cutting off some digits.
=> Add wide card layout

packages/app/client/src/ui/editor/emulator/parts/log/log.scss, packages/app/client/src/ui/editor/emulator/parts/log/log.scss.d.ts, packages/app/client/src/ui/editor/emulator/parts/log/log.tsx, packages/app/client/src/ui/styles/themes/dark.css, packages/app/client/src/ui/styles/themes/high-contrast.css, packages/app/client/src/ui/styles/themes/light.css, packages/app/client/webpack.config.js
Fix for #510 
---
Log entries now have a hover state and 'inspected' state. When clicking an activity in Webchat, the corresponding log entry will enter the 'inspected' state and be colored. Hovering over a log entry will now also highlight the corresponding Webchat activity if possible.
=> Added corresponding Webchat activity / log entry highlighting

packages/app/client/src/data/action/botActions.ts, packages/app/client/src/data/sagas/botSagas.ts, packages/app/client/src/data/sagas/index.ts, packages/app/client/src/ui/shell/explorer/botExplorerBar/botExplorerBar.tsx, packages/app/client/src/ui/shell/explorer/botNotOpenExplorer/botNotOpenExplorer.scss, packages/app/client/src/ui/shell/explorer/botNotOpenExplorer/botNotOpenExplorer.scss.d.ts, packages/app/client/src/ui/shell/explorer/botNotOpenExplorer/botNotOpenExplorer.tsx, packages/app/client/src/ui/shell/explorer/botNotOpenExplorer/botNotOpenExplorerContainer.ts, packages/app/client/src/ui/shell/explorer/botNotOpenExplorer/index.ts, packages/app/client/src/ui/shell/explorer/index.ts, packages/app/client/src/ui/shell/main.tsx, packages/app/client/webpack.config.js
Fix for #645 
---
- Added `Open Bot` button to bot explorer empty state
- Also increased the minimum width threshold that determines when the explorer hides when dragged (more similar behavior to VS Code)
=> Added 'Open Bot' button to empty bot explorer.

packages/app/client/src/data/action/editorActions.ts, packages/app/client/src/data/reducer/editor.spec.ts, packages/app/client/src/data/reducer/editor.ts, packages/app/client/src/ui/shell/multiTabs/tabbedDocument/leftContentOverlay/leftContentOverlay.tsx
Fix for #531 
========
Dragging a tab onto the left side of the editor when only one editor is open, will place that tab in the left tab group, and move all other open tabs to the right tab group.
=> Implemented left-side overlay drag n drop.

packages/app/client/src/ui/shell/main.tsx
Fix for #743 
==========
Bumped up default explorer pane size to `280px`. Will now accommodate a notification with two buttons.
Calculation:
- `20px` padding on left and right sides of notification pane
- `12px` padding on left and right sides of each notification
- allow for 2 buttons of width `104px`
- allow for `8px` margin between buttons
`(20px * 2) + (12px *2) + (104px * 2) + 8px = 280px`
=> Increased default size of explorer pane.

packages/app/client/src/data/action/chatActions.ts, packages/app/client/src/data/reducer/chat.spec.ts, packages/app/client/src/data/reducer/chat.ts, packages/app/client/src/ui/editor/emulator/chatPanel/chatPanel.tsx, packages/app/client/src/ui/editor/emulator/emulator.tsx, packages/app/client/src/ui/editor/emulator/logPanel/logPanel.tsx
Fix for #705 
===========
- Pressing `Ctrl` + `Shift+ `R` or `Cmd` + `Shift+ `R` with a chat session open will now restart that conversation
- Also fixed the chat panel header. We were trying to read the endpoint from an outdated property, and the endpoint should now once again be visible in the header
=> Added hotkey (Ctrl/Cmd + Shift + R) for starting a conversation over.

packages/app/client/src/data/reducer/editor.spec.ts, packages/app/client/src/ui/editor/welcomePage/index.ts, packages/app/client/src/ui/editor/welcomePage/welcomePage.scss, packages/app/client/src/ui/editor/welcomePage/welcomePage.scss.d.ts, packages/app/client/src/ui/editor/welcomePage/welcomePage.tsx, packages/app/client/src/ui/editor/welcomePage/welcomePageContainer.ts, packages/app/main/src/botHelpers.spec.ts, packages/app/main/src/botHelpers.ts, packages/app/main/src/commands/botCommands.ts, packages/app/shared/src/constants/sharedConstants.ts
Fix for #619 
============
Hovering over an entry in the `My Bots` list will now show a minus button that can be clicked to delete the entry (this **will not delete** the corresponding `.bot` file)
**Note:** Still needs final design specs, but everything is wired up. Might need to add a confirmation dialog.
=> Added UI to delete bots from bots list

packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.tsx
Fix for #677 
============
Couldn't use the suggested text in the issue because it gets truncated due to the max width of the dialog
=> Improved bot endpoint input placeholder text.

packages/app/client/src/ui/editor/botSettingsEditor/botSettingsEditor.tsx, packages/app/main/src/botHelpers.spec.ts, packages/app/main/src/botHelpers.ts
Fixes for broken encryption flows:
- Added Checkbox that will toggle the `Bot Secret` input on the Bot Settings page between a clear-text 
& password input so the user can see what they are typing
- the function `toSavableBot()` wasn't copying over the `secretKey` property so it was being erased every time the bot was saved, which was breaking encryption when services were added
- `msbot` library functionality changed so it now silently loads an encrypted bot without complaining, so our secret prompt logic was no longer being hit. `loadBotWithRetry()` will now check if the loaded bot file has a `secretKey` property and if it was passed a secret before trying to decrypt
=> Fixed bot file encryption issues.

package-lock.json, packages/app/client/package.json
Will fix #564.
I found that `/package-lock.json` keep updating and I can't get it to a small change.
On my NPM 6.4.0, I did:
```
git clone …
npm install
lerna add botframework-webchat@0.14.2 --scope=@bfemulator/client --hoist
npm run bootstrap
```
If I do `npm run bootstrap` first, then `lerna add` later. We will get some errors about missing peer dependencies on `@uifabric/*` while doing `lerna add`. Since it's out of the scope for this PR, I am doing it the other way first.
=> Bump to botframework-webchat@0.14.2

packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.tsx
Before, when creating a new bot, the endpoint created with it had a blank name which would show up as blank in the endpoint explorer. Now it uses the endpoint's url as the name.
=> A newly created bot will now fill out the endpoint name with its url.

packages/emulator/core/src/conversations/middleware/sendActivityToConversation.ts, packages/emulator/core/src/conversations/middleware/sendHistoryToConversation.ts, packages/emulator/core/src/conversations/registerRoutes.ts, packages/emulator/core/src/types/activity/conversationHistory.ts
The PR has the changes to implement the "UploadHistory" API that's added to DirectLine. This ensures that bots do not get an error when they try to upload history while running against the emulator.
Changes:
1. Renamed sendToConversation to sendActivityToConversation
2. Added sendHistoryToConversation to implement the history upload API that's supported by DirectLine
=> Conversation history API

packages/app/client/src/ui/styles/themes/dark.css, packages/app/client/src/ui/styles/themes/light.css, packages/app/client/src/ui/styles/themes/neutral.css
Related to issue [703: [MAS1.4.3] Luminosity Contrast Ratio of text in grey present in Log panel is less than required 4.5:1.](https://github.com/Microsoft/BotFramework-Emulator/issues/703)
- Update Neutral-6 color to #9E9E9E
- Make Light theme log debug text #666 
- Make Dark theme log debug text #9E9E9E
=> Update log debug text to meet contrast ratio requirements

.travis.yml, generate_releases.sh, package.json
- Enabled Travis Deployments using GitHub Releases
- after_success: check if it is a Cron Job and generates a new tag name.
- before_deploy: run script to generate binaries (this is work in progress) and set the TRAVIS_TAG env var.
- deploy: creates a new Release including binaries files, name and description. It marks it as Pre-Release.
- condition: Release will be created for branch `v4` only and for Cron Jobs only.
- additionally, devDependencies wehre updated with those installed globally in before_install
=> Enable Travis deployment releases

packages/sdk/ui-react/src/widget/checkbox/checkbox.styles.ts, packages/sdk/ui-react/src/widget/textField/textField.tsx
In reference to latest comments on [#740: Check-boxes present in 'Emulator Settings' pane are not accessible using keyboard.](https://github.com/Microsoft/BotFramework-Emulator/issues/740)
- Checkboxes' accessibility was fixed in an earlier PR to v4 (enter and space both work to flip checked value & focus is visible)
- Hover/focus text in dark theme and high contrast theme has been updated 
- Textfield text (input labels) color now displays correct color
=> Update checkbox and textfield colors on Settings page in dark theme & high contrast theme

packages/app/client/src/ui/editor/emulator/parts/chat/chat.spec.ts, packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx
This will fix #606. We should use `endpoint.id` to identify an endpoint instead of `endpoint.endpoint`.
=> Fix #606 Use endpoint ID

packages/app/client/src/ui/shell/explorer/notificationsExplorer/notification.scss, packages/app/main/src/migrator.spec.ts, packages/app/main/src/migrator.ts
Fix for #798 
=========
Migration will no longer run for fresh V4 installs since it will now first check if the `%emulator_data%/migration/` folder exists. (which should only ever exist post-v3-migration)
Also fixed text wrapping inside of notifications so that text can longer bleed out of the notification element
=> Disabled migration on fresh v4 installs; fixed notification text wrapping

packages/app/client/src/ui/shell/main.tsx, packages/app/client/src/ui/shell/navBar/navBar.tsx
Workaround for #825 
============
Disabled ability to toggle explorer so that webchat can no longer be reset.
Current proposed solution is to keep an instance of webchat around in a separate div, and then mount it to the livechat UI when necessary.
The above solution would also fix the issue where webchat is reset if splitting the livechat tab while active.
=> Temporarily disabled toggling explorer until webchat reset bug is fixed.

packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.scss, packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.tsx, packages/app/client/src/ui/dialogs/botSettingsEditor/botSettingsEditor.scss, packages/app/client/src/ui/dialogs/botSettingsEditor/botSettingsEditor.tsx, packages/app/client/src/ui/dialogs/botSettingsEditor/botSettingsEditorContainer.ts
Fixes for #908 
========
- Made changes to `BotCreation` and `SecretPrompt` dialogs
- Changed some strings
- Added a `Learn More` link about encryption next to checkbox
- Added placeholder text to empty secret input
- Unchecking the checkbox no longer hides the secret UI
=> Encryption UI Fixes

packages/app/client/src/vendors.ts, packages/extensions/luis/client/src/App.tsx
design is needed here when the api call fails. There is currently no notification to the user that `train` or `publish` has failed.
=> #920 - fixed the spinner remaining when an api call to luis fails

packages/app/client/src/ui/shell/mdi/tab/tab.scss
Resolves #715 
- change visibility: visible/hidden to opacity 1/0 - this change is necessary to make the close button accessible via tab/shift+tab when moving between keyboard focus on a (non-active) close button to (active) tab and vice versa.
- change mask to sit within the span because for whatever reason borders (needed for focus) don't appear on masks.
=> Add fix to tabs where close button was not keyboard accessible

.travis.yml
this change will stop travis uploaded builds to GitHub from being tagged as pre-release.  they'll now be tagged as draft
=> stop travis build from publishing pre-release tagged builds

packages/app/client/webpack.config.js
This fixes #993  without affecting the local dev environment or requiring an increase to the data url threshold.
=> #993 - removed localhost designation from build

packages/app/main/src/ngrokService.ts
Currently, bypass is `undefined` when the `getServiceUrl(botUrl: string): string` method is called. Reusing the logic we use to keep address and port in sync with the state. *This entire piece of logic should be refactored, adding a surgical fix for now. *
Fixes #974
=> Ngrok bypass: simple fix to have the bypass setting up to date with the state.

packages/sdk/ui-react/src/layout/expandCollapse/expandCollapse.scss
Clicking the arrow on the `<ExpandCollapse>` control was not triggering the expanded state to change because it was floating in the margin.
=> Fixed hit target for expand collapse control.

CONTRIBUTING.md
Since master now has the v4 emulator, the information about checking out the v4 branch is out of date in the CONTRIBUTING.md. The community will probably want to develop against master.
=> remove v4 branch instructions in CONTRIBUTING.md

packages/app/main/src/commands/azureCommands.ts, packages/app/main/src/services/azureAuthWorkflowService.spec.ts, packages/app/main/src/services/azureAuthWorkflowService.ts
Authentication changes:
- Move to Bot Framework first party app
- On the app side, requested a change that jst got approved to allow implicit flow
- Implicit flow docs: [oauth spec ](https://tools.ietf.org/html/rfc6749#section-1.3.2) and [aad docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-oauth2-implicit-grant-flow).
- Implicit flow returns the access token directly but to a reply uri approved by the app. We just intercept the request and extract the token from the url
2 factor auth in progress
Phone authentication
Querying luis models after successful auth
Querying QnA resources
Hotmail MFA password
Hotmail device authentication with Authenticator app
Live specific remember account to bypass 2fa in the future
Successful signin iwth hotmail
=> Authentication: Move to first party app and change flow to implicit flow.

packages/app/main/package-lock.json, packages/app/main/package.json
Fix for #1175
===
When proxy support was added, we forgot to add the above dependency
Since this bug breaks the Emulator for users behind a proxy, I'm requesting PR against 4.2 so that we can cut a new build, 4.2.1, with this fix.
=> Added missing https-proxy-agent dependency.

package-lock.json, packages/app/client/src/data/sagas/botSagas.spec.ts, packages/app/client/src/data/sagas/botSagas.ts, packages/app/client/src/data/sagas/editorSagas.spec.ts, packages/app/client/src/data/sagas/editorSagas.ts, packages/app/client/src/data/sagas/sharedSagas.spec.ts, packages/app/client/src/data/sagas/sharedSagas.ts, packages/app/main/src/appMenuBuilder.spec.ts, packages/app/main/src/appMenuBuilder.ts, packages/app/main/src/commands/electronCommands.spec.ts, packages/app/main/src/commands/electronCommands.ts, packages/app/main/src/main.ts
Fix for #1157 
===
**Same PR as before with suggested changes integrated**
--- 
Switching between tabs when a livechat session was open was having a major performance issue because of sending the entire client state over IPC multiple times.
This PR fixes that performance issue, rewrites `appMenuBuilder.ts` to allow us to change parts of the native app menu without reconstructing the entire thing, and adds some much needed tests.
=> Fixed tab switching performance issue

packages/app/client/src/ui/editor/welcomePage/welcomePage.scss
closes #1205 
also fixes an issue where some links were being clipped on smaller view ports.
=> fix step alignment issue on small viewports

packages/app/main/src/restServer.ts, packages/emulator/core/src/middleware/getBotEndpoint.spec.ts, packages/emulator/core/src/middleware/getBotEndpoint.ts, packages/emulator/core/src/utils/botFrameworkAuthentication.ts
This PR fixes #1212 and provides unit tests for the offending code. A `404` is now properly delivered when the oauth token does not exist.
=> Fixed #1212 - Emulator fails to respond to OAuth emulation request

CONTRIBUTING.md
I was contacted by an internal employee today that had some difficulty understanding some parts of the `CONTRIBUTING.md` instructions -- mainly debugging the client side -- because some of the info is unnecessary and / or outdated.
Removed some redundant sections and made some minor corrections.
=> Updated Contributing instructions.

.editorconfig, .gitattributes, .github/CODEOWNERS
This makes developing on multiple platforms easier by allowing git to control which line endings to use on the host system.
EDIT: also adds `CODEOWNERS` file for automatic review requests.
=> let git handle line endings instead of editor

package-lock.json, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.scss, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.spec.tsx, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.tsx, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialogContainer.ts, packages/app/client/src/ui/helpers/activeBotHelper.spec.ts, packages/app/client/src/ui/helpers/activeBotHelper.ts, packages/app/client/src/ui/shell/explorer/botNotOpenExplorer/botNotOpenExplorer.scss, packages/app/client/src/ui/shell/explorer/botNotOpenExplorer/botNotOpenExplorer.scss.d.ts, packages/app/client/src/ui/shell/explorer/botNotOpenExplorer/botNotOpenExplorer.spec.tsx, packages/app/client/src/ui/shell/explorer/botNotOpenExplorer/botNotOpenExplorer.tsx, packages/app/client/src/ui/shell/explorer/botNotOpenExplorer/botNotOpenExplorerContainer.ts, packages/sdk/ui-react/src/widget/dialog/dialog.scss
=> #1237 - added new copy and updated functionality

CHANGELOG.md, packages/app/main/src/appMenuBuilder.spec.ts, packages/app/main/src/appMenuBuilder.ts, packages/app/main/src/commands/botCommands.ts, packages/app/main/src/main.ts, packages/app/main/src/utils/platform.spec.ts, packages/app/main/src/utils/platform.ts
closes #1239 
On a mac, the `radio` type UI is the exact same as `checkbox` type, but functions correctly. This has not effect on Windows or Linux.
=> Fix theme menu state on mac

.eslintrc.js, CHANGELOG.md, packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.scss, packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.scss.d.ts, packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.spec.tsx, packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.tsx
closes #1127 
closes #1223 
- [client] Show a message when nothing has been inspected yet, in PR [#1290](https://github.com/Microsoft/BotFramework-Emulator/pull/1290)
=> show message when nothing has been inspected yet

CHANGELOG.md, packages/app/client/src/ui/shell/explorer/endpointExplorer/endpointEditor/endpointEditor.spec.tsx, packages/app/client/src/ui/shell/explorer/endpointExplorer/endpointEditor/endpointEditor.tsx, packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/connectedServiceEditor.spec.tsx, packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/connectedServiceEditor.tsx
As per discussion in #1277 
====
=> Renamed 'submit' button to 'save' in endpoint & service editors.

.vscode/launch.json, CHANGELOG.md, packages/app/client/src/data/sagas/servicesExplorerSagas.spec.ts, packages/app/client/src/data/sagas/servicesExplorerSagas.ts, packages/app/main/src/services/qnaApiService.spec.ts, packages/app/main/src/services/qnaApiService.ts
closes #1286 
closes #1287 
closes #1289 
- [main] use correct values for subscriptionKey and endpointKey for qna services, in PR [#1301](https://github.com/Microsoft/BotFramework-Emulator/pull/1301)
- [client] fix link to manage qna service, in PR [#1301](https://github.com/Microsoft/BotFramework-Emulator/pull/1301)
=> use correct values for subscriptionKey and endpointKey for qna services

CHANGELOG.md, packages/app/client/src/hyperlinkHandler.spec.ts, packages/app/client/src/hyperlinkHandler.ts, testSetup.js
=> Data url links will now prompt to save to disk.

packages/app/main/scripts/mac.js
Noticed that `latest-mac.yml` wasn't in the artifacts list of the nightly releases. The script generating the file was throwing but not failing the build step.
=> Fixed issue preventing latest-mac.yml from being generated.

packages/app/client/src/ui/editor/welcomePage/howToBuildABot.tsx
There was a space inside one of the links and it looks wonky. Made a fix!
Previous appearance of hovering on Continuous Deployment link:
Current appearance:
=> Nitpick UI fix of Welcome Page anchor

CHANGELOG.md, packages/app/client/src/ui/editor/emulator/emulator.tsx
=> Fixed issue where restart conversation was not clearing history.

CHANGELOG.md, packages/app/client/src/ui/editor/emulator/emulator.spec.tsx, packages/extensions/luis/client/src/Adapters/AppStateAdapter.tsx, packages/extensions/luis/client/src/App.tsx, packages/extensions/qnamaker/client/src/AppStateAdapter.tsx, packages/sdk/shared/src/types/activity/trace.ts
Fixes #1328 
(Also fixed broken `emulator.spec.tsx` unit tests that were caused by PR #1325)
===
`TraceActivity` definition wasn't even in the codebase anymore, so I added it back.
**NOTE:** This is a short-term fix. For a long-term fix, I think we should make the `sdk-shared` package agnostic to the JS environment (node / browser). That action item is tracked here #1333.
=> Fixed broken luis inspector.

CHANGELOG.md, packages/app/client/src/ui/editor/emulator/parts/chat/chat.spec.tsx, packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx, packages/app/client/src/ui/editor/emulator/parts/chat/chatContainer.ts
fixes #1350 
- [client] Pass along user name to webchat in PR [#1353](https://github.com/Microsoft/BotFramework-Emulator/pull/1353)
=> pass username to webchat

CHANGELOG.md, packages/emulator/core/src/directLine/middleware/upload.ts
Fixes #1362
===
Also moved the service url declaration out of the for loop so that it's not unnecessarily generated for every item.
=> Fixed issue with contentUrl for attachments.

CHANGELOG.md, packages/app/main/src/commands/botCommands.ts, packages/app/main/src/commands/electronCommands.ts, packages/app/main/src/main.ts, packages/emulator/core/src/utils/oauthLinkEncoder.ts
=> Fixes #1283 - opening a bot that has moved should show a message

CHANGELOG.md, packages/app/client/src/ui/editor/emulator/parts/chat/chat.scss, packages/app/client/src/ui/styles/themes/dark.css, packages/app/client/src/ui/styles/themes/high-contrast.css, packages/app/client/src/ui/styles/themes/light.css
Fixes #1327 
===
Added styling for scrollbar within the Webchat panel, so that it is now visible.
Light:
Dark:
High Contrast:
=> Added visible scrollbar styling for webchat panel.

CHANGELOG.md, packages/app/main/src/commands/emulatorCommands.spec.ts, packages/app/main/src/commands/emulatorCommands.ts
=> Fixed issue where userId was out of sync between bot and user.

CHANGELOG.md, packages/app/client/src/ui/styles/themes/dark.css, packages/app/client/src/ui/styles/themes/high-contrast.css, packages/app/client/src/ui/styles/themes/light.css, packages/sdk/ui-react/src/widget/dialog/dialog.scss
Fixes issue #1312 
- Update `.dialog`  _color_ and _bg-color_ of the high-contrast theme to match the theme's palette.
=> [Style] Update modals to increase readability on High-Contrast Theme

CHANGELOG.md, packages/app/client/src/ui/dialogs/secretPromptDialog/secretPromptDialog.scss, packages/app/client/src/ui/dialogs/secretPromptDialog/secretPromptDialog.scss.d.ts, packages/app/client/src/ui/dialogs/secretPromptDialog/secretPromptDialog.tsx
The secret prompt dialog had an opaque background which blocked out all of the underlying app.
===
Before:
After:
=> Fixed secret prompt dialog's opaque background.

CHANGELOG.md, packages/sdk/ui-react/src/widget/checkbox/checkbox.scss, packages/sdk/ui-react/src/widget/checkbox/checkbox.scss.d.ts, packages/sdk/ui-react/src/widget/checkbox/checkbox.tsx
=> Added default disabled styling to checkbox control.

CHANGELOG.md, packages/app/client/src/ui/editor/panel/panel.scss, packages/app/client/src/ui/shell/explorer/explorerStyles.scss, packages/app/client/src/ui/shell/mdi/tab/tab.scss, packages/app/client/src/ui/shell/mdi/tab/tab.scss.d.ts, packages/app/client/src/ui/shell/mdi/tab/tab.spec.tsx, packages/app/client/src/ui/shell/mdi/tab/tab.tsx
Fixes #1228. Also fixes the incorrect styling of the bot explorer.
===
---
=> Fixed tab icons

package-lock.json, packages/app/client/src/commands/emulatorCommands.ts, packages/app/client/src/data/action/botActions.ts, packages/app/client/src/data/action/chatActions.ts, packages/app/main/src/restServer.spec.ts, packages/app/main/src/restServer.ts, packages/app/shared/src/types/conversationTypes.ts, packages/emulator/core/package.json, packages/emulator/core/src/conversations/middleware/createConversation.ts, packages/emulator/core/src/facility/conversation.ts, packages/emulator/core/src/facility/conversationSet.ts, packages/extensions/json/index.html, packages/sdk/shared/src/types/activity/startConversationParams.ts
We need the ability to know if a conversation was started when connected from a url, or started from a .bot file endpoint. This will set the stage for wrapping up the sidecar debugging feature.
=> Drill livechat mode

packages/app/main/src/botHelpers.spec.ts, packages/app/main/src/botHelpers.ts, packages/app/main/src/commands/emulatorCommands.spec.ts, packages/app/main/src/commands/emulatorCommands.ts, packages/emulator/core/src/conversations/middleware/createConversation.ts
As it stands, the transcript path for a conversation opened via url is incorrect when there is an active bot opened via .bot file. With #1438 it enables this change to support saving transcripts in both .bot file conversations and conversations opened via url.
=> Save transcript fix

CHANGELOG.md, packages/app/main/src/protocolHandler.spec.ts, packages/app/main/src/protocolHandler.ts
=> Fixed opening a livechat session via protocol.

CHANGELOG.md, packages/emulator/core/src/directLine/middleware/startConversation.ts, packages/emulator/core/src/facility/conversation.ts
As a side effect of bumping Electron a new node deprecation warning has surfaced. This fixes it.
=> Got rid of node Buffer() deprecation warnings.

CHANGELOG.md, CONTRIBUTING.md, package-lock.json, packages/app/client/src/data/sagas/azureAuthSaga.ts, packages/app/client/src/data/sagas/botSagas.spec.ts, packages/app/client/src/data/sagas/botSagas.ts, packages/app/client/src/data/sagas/chatSagas.ts, packages/app/client/src/data/sagas/editorSagas.spec.ts, packages/app/client/src/data/sagas/editorSagas.ts, packages/app/client/src/data/sagas/endpointSagas.ts, packages/app/client/src/data/sagas/frameworkSettingsSagas.spec.ts, packages/app/client/src/data/sagas/frameworkSettingsSagas.ts, packages/app/client/src/data/sagas/navBarSagas.spec.ts, packages/app/client/src/data/sagas/navBarSagas.ts, packages/app/client/src/data/sagas/notificationSagas.spec.ts, packages/app/client/src/data/sagas/notificationSagas.ts, packages/app/client/src/data/sagas/resourcesSagas.ts, packages/app/client/src/data/sagas/servicesExplorerSagas.ts, packages/app/client/src/data/sagas/sharedSagas.spec.ts, packages/app/client/src/data/sagas/sharedSagas.ts, packages/app/client/src/data/sagas/welcomePageSagas.ts, packages/app/client/src/ui/helpers/activeBotHelper.ts, packages/app/main/package.json, packages/app/main/src/botHelpers.spec.ts, packages/app/main/src/commands/emulatorCommands.spec.ts, packages/app/main/src/protocolHandler.ts, packages/app/main/src/settingsData/sagas/settingsSagas.ts
=> Added npm script to watch and auto-restart the main process.

packages/extensions/botState/bf-extension.json, packages/extensions/botState/src/WindowHostReceiver.ts
Part of #1443 
===
Behavior is that on first inspect of a BotState trace, the inspector will default to the JSON viewer mode, however, on every subsequent inspect, it will use whatever the previous mode was.
Ex:
Inspect BotState A  ----> JSON view
Inspect BotState B ------> JSON view
Switch to Graph view
Inspect BotState C ------> Graph view
=> Bot state visualizer now defaults to JSON viewer.

packages/app/client/src/ui/editor/emulator/emulator.tsx
Part of #1443 
===
QoL improvement related to the strange slider behavior caused by the Chromium `<webview>` issue that eats mouse events.
=> Gave webchat panel a minimum width of 200px.

packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.spec.tsx, packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.tsx, packages/app/client/src/ui/editor/emulator/parts/inspector/inspectorContainer.ts, packages/app/main/src/commands/emulatorCommands.spec.ts, packages/app/main/src/settingsData/sagas/settingsSagas.spec.ts, packages/app/main/src/settingsData/sagas/settingsSagas.ts, packages/app/shared/src/types/clientAwareSettings.ts
One of #1443 
===
Now use Electron `app.getAppPath()` API and is fed through the main side to the client on app start.
=> Fixed preload script path hack.

CHANGELOG.md, packages/app/client/src/data/sagas/botSagas.spec.ts, packages/app/client/src/data/sagas/botSagas.ts, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.scss, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.scss.d.ts, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.spec.tsx, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.tsx, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialogContainer.ts, packages/app/client/src/ui/styles/themes/dark.css, packages/app/client/src/ui/styles/themes/high-contrast.css, packages/app/client/src/ui/styles/themes/light.css, packages/app/main/src/commands/settingsCommands.spec.ts, packages/app/main/src/commands/settingsCommands.ts, packages/app/main/src/settingsData/actions/savedBotUrlsActions.spec.ts, packages/app/main/src/settingsData/actions/savedBotUrlsActions.ts, packages/app/main/src/settingsData/reducers/index.ts, packages/app/main/src/settingsData/reducers/savedBotUrlsReducer.spec.ts, packages/app/main/src/settingsData/reducers/savedBotUrlsReducer.ts, packages/app/main/src/settingsData/sagas/settingsSagas.ts, packages/app/shared/src/constants/sharedConstants.ts, packages/app/shared/src/types/clientAwareSettings.ts, packages/app/shared/src/types/serverSettingsTypes.ts, packages/sdk/ui-react/src/widget/autoComplete/autoComplete.scss, packages/sdk/ui-react/src/widget/autoComplete/autoComplete.scss.d.ts, packages/sdk/ui-react/src/widget/autoComplete/autoComplete.spec.tsx, packages/sdk/ui-react/src/widget/autoComplete/autoComplete.tsx
One of #1443 
===
Don't worry, I'll squash all of the commits.
@mewa1024 I just used the styling from the Split Button drop down specs
=> Implemented autocomplete functionality in open bot dialog

scripts/PublishToCoveralls.ps1
For publishing the coveralls report to the coveralls site. This to be run in a release pipeline like Upload-Coveralls-Results-from-DotNet-CI https://fuselabs.visualstudio.com/SDK_v4/_releaseDefinition?definitionId=20&_a=environments-editor-preview
=> Add PublishToCoveralls.ps1

package.json
Trying to write coverage report to disk.
This works: npm run test -- --coverage --coverageReporters=lcov --coverageReporters=text
This did not: npm run test --coverage --coverageReporters=lcov --coverageReporters=text
=> Fix test:gen-lcov script

packages/sdk/ui-react/src/widget/textField/textField.tsx
Fixes #1520 
`inputProps` ordering should be reversed to give priority to props passed in.
=> Fixed #1520

CHANGELOG.md, packages/sdk/ui-react/src/widget/autoComplete/autoComplete.spec.tsx, packages/sdk/ui-react/src/widget/autoComplete/autoComplete.tsx
=> Fixed autocomplete losing focus after selecting result with mouse.

CHANGELOG.md, packages/app/client/src/ui/shell/mdi/tab/tab.scss
=> Fixed shrinking of tab icon on sidecar docs page.

CHANGELOG.md, packages/app/main/package.json
Fixes #1537 
===
The issue was caused by the Emulator installer.exe requiring admin permissions to run because it installed on a per-machine (for all users) basis. I've changed the installer to be on a per-user basis, so it no longer requires admin permissions to run. So now the update will be installed after closing the emulator, regardless of whether it was running in an administrator context or not.
Top installer is with the new change, bottom is without:
=> Changed NSIS installer to install on a per-user basis.

packages/app/client/src/ui/editor/emulator/emulator.tsx, packages/app/main/package-lock.json
This should fix the issue where the userId from settings was not propagating to new conversations
=> Fixed user id issue.

CHANGELOG.md, packages/app/main/package-lock.json, packages/app/main/package.json
Bumped package version to `4.4.2` and corrected changelog (entries for 4.4.2 were being placed under 4.4.1 header)
=> Prep for version 4.4.2.

packages/sdk/ui-react/src/widget/autoComplete/autoComplete.scss
Fixes #1607 
Updated the _CSS_ properties of the **AutoComplete** component to be able to truncate the text with an ellipsis when the text is too long.
=> Autocomplete Results Wrap if Too Long 

package-lock.json, packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.spec.tsx, packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.tsx, packages/app/main/src/extensions/inspector-preload.js, packages/sdk/shared/src/types/log/item.ts
This PR relates to #1565 and provides all the necessary data to the extension in order to complete this feature.
Emulator extensions can now receive all chat log entries (array of [LogEntry](https://github.com/microsoft/BotFramework-Emulator/blob/master/packages/sdk/shared/src/types/log/entry.ts#L36)) if interested.
To enable an Extension to receive the chat logs, it must subscribe to the `chat-log-updated` event on the `window.host` object. e.g. 
```js
// ...
window.host.on('chat-log-updated', (conversationId: string, logEntries: LogEntry[]) => {
// Do stuff
}):
```
Or if your extension contains the `WindowHostReceiver` class, decorate the handler with the `chat-log-updated` event type. e.g.
```js
//...
@IpcHandler('chat-log-updated')
protected chatLogUpdatedHandler(conversationId: …
```
=> Updated the inspector and IPC hooks to surface chat log data

packages/app/client/src/ui/dialogs/updateAvailableDialog/updateAvailableDialog.scss, packages/app/client/src/ui/dialogs/updateAvailableDialog/updateAvailableDialog.scss.d.ts, packages/app/client/src/ui/dialogs/updateAvailableDialog/updateAvailableDialog.spec.tsx, packages/app/client/src/ui/dialogs/updateAvailableDialog/updateAvailableDialog.tsx, packages/app/client/src/ui/dialogs/updateAvailableDialog/updateAvailableDialogContainer.ts, packages/app/client/src/ui/styles/themes/dark.css, packages/app/client/src/ui/styles/themes/high-contrast.css, packages/app/client/src/ui/styles/themes/light.css, packages/app/main/src/appUpdater.spec.ts, packages/app/main/src/appUpdater.ts, packages/app/shared/src/types/serverSettingsTypes.ts
Resolves #1408 
===
This PR includes the following changes to app update logic:
1. **Auto update must be explicitly opted into now**
1. The app will always check for updates on startup, regardless of auto update or not
1. If there are updates, and auto update is not enabled, the following modal will be shown:
(option 2 is always selected by default, and option 3 will enable auto updates)
**Light**
**Dark**
**High Contrast**
=> Changed App Update UX & Made Auto Updates Opt-In

packages/app/client/src/ui/shell/main.scss, packages/app/client/src/ui/styles/themes/dark.css, packages/app/client/src/ui/styles/themes/high-contrast.css, packages/app/client/src/ui/styles/themes/light.css
Fixes #1508
- Add background image in the dialog explorer
- Fix dialog-bg color in dark theme
=> Add background image for when there are no tabs open

CHANGELOG.md, package.json, packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditor.tsx, packages/app/main/src/telemetry/telemetryService.ts
Re-enabled the option to start collecting usage data & telemetry.
Also added an extra safeguard to guarantee that unit tests do not trigger telemetry to be collected.
=> Re-enabled telemetry.

packages/app/client/src/data/sagas/servicesExplorerSagas.spec.ts, packages/app/client/src/data/sagas/servicesExplorerSagas.ts, packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServicePicker/connectedServicePicker.scss, packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServicePicker/connectedServicePicker.scss.d.ts, packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServicePicker/connectedServicePicker.tsx, packages/app/client/src/ui/shell/explorer/servicesExplorer/servicesExplorer.tsx, packages/app/main/src/services/cosmosDbApiService.ts, packages/app/main/src/services/storageAccountApiService.spec.ts, packages/app/main/src/services/storageAccountApiService.ts
Fixes: #1495
- Fix Azure Storage deep links
- Fix Cosmos DB deep links
- Fix storageAccountApiService bug where container name was not saved to bot file
- Fix CosmosDbApiService bug where `collection.id` was also saved as the `service.serviceName`
- Update servicesExplorer to render  Cosmos DB and Storage resources as `Service-Name - Container/Collection-Name`
- Fix incorrect text in connectedServicePicker for Cosmos DB render when no Cosmos DB resources are found
- Update connectedServicePicker to render the service name and the container/collection (Cosmos DB and Storage Account only)
___
Final:
=> Fix Azure Storage and Cosmos DB Deep Links - #1495

CHANGELOG.md, packages/app/main/src/appUpdater.spec.ts, packages/app/main/src/commands/ngrokCommands.ts, packages/app/main/src/main.ts, packages/app/main/src/ngrok.spec.ts, packages/app/main/src/ngrok.ts, packages/app/main/src/ngrokService.spec.ts, packages/app/main/src/ngrokService.ts, packages/app/main/src/protocolHandler.spec.ts, packages/app/main/src/protocolHandler.ts, packages/app/main/src/restServer.ts, packages/emulator/cli/src/index.ts, packages/emulator/core/src/botEmulator.spec.ts, packages/emulator/core/src/botEmulator.ts, packages/emulator/core/src/userToken/middleware/tokenResponse.ts, packages/emulator/core/src/utils/oauthLinkEncoder.spec.ts, packages/emulator/core/src/utils/oauthLinkEncoder.ts, packages/extensions/luis/client/src/Luis/Client.spec.ts
Fixes #1544 
===
This will fix the issue users were having when trying to authenticate via an OAuth prompt card as seen in samples [18](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/18.bot-authentication) and [24](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/24.bot-authentication-msgraph).
`ngrok.ts` has been rewritten so that instead of being a singleton, it is now a class that can be instantiated multiple times to represent individual ngrok instances.
This fix checks to see if ngrok is already running when generating the postback URL for the OAuth sign in flow. If ngrok is already running, then that ngrok URL is used as the postback URL, if not, we start up a separate ngrok instance solely for the purpose …
=> Fixed OAuth card prompt flow

CHANGELOG.md, packages/emulator/core/src/attachments/middleware/getAttachment.ts
Fixes #1362 
===
The issue was that the attachment data sent from a bot is already an encoded base64 string, and is not a buffer that needs to be converted, whereas attachments uploaded via the Web Chat client's paperclip button arrive as a buffer that needs to be converted.
The latter case was fixed in #1364.
This will fix the former case.
**Uploading image from bot code:**
**Uploading image from Web Chat client control:**
=> Fixed handling of attachments sent from a bot.

packages/app/client/src/ui/editor/emulator/emulator.spec.tsx, packages/app/client/src/ui/editor/emulator/emulator.tsx, packages/app/client/src/ui/editor/emulator/emulatorContainer.ts, packages/app/main/src/botHelpers.spec.ts
Users should no longer see multiple tuples of conversation updates being sent when opening a livechat via a URL for the first time.
=> Fixed issue where conversation was being started multiple times.

packages/emulator/core/src/conversations/middleware/getBotEndpoint.ts
Fixes #1622
The existing validations ([here](https://github.com/microsoft/BotFramework-Emulator/blob/88bfc5531e8a2c45db4a6f790db78abbb1f5b68b/packages/emulator/core/src/conversations/middleware/getBotEndpoint.ts#L70-L75)) were not taking into account the case in which a user wants to connect a bot to the emulator using the same endpoint without credentials. We remove the validations to able to rewrite the existing credentials with no contents in this case. 
- Remove validations to be able to connect a bot without credentials
We following the steps to reproduce the issue and the bots were connected successfully.
=> [ISSUE#1622] Can't open new tab with same endpoint URL by clicking the endpoint

packages/app/client/src/ui/dialogs/openUrlDialog/openUrlDialog.scss, packages/app/client/src/ui/dialogs/openUrlDialog/openUrlDialog.scss.d.ts, packages/app/client/src/ui/dialogs/openUrlDialog/openUrlDialog.tsx
Fixed some minor styling issues with the open url dialog:
- long links were not wrapping properly
- buttons were overflowing out of dialog
**Before:**
**After (long link):**
**After (short link):**
=> Adjusted open url dialog styling.

packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.tsx, packages/extensions/luis/client/webpack.config.js
- There was some code inside of `inspector.tsx` that was causing buttons from the last inspector to be used for the current inspector regardless of if they were the same inspector or not. I added some code that ensures that the inspectors have the same name before reusing the buttons.
- Also mocked a global `process` variable inside of the LUIS extension so that MSRest (dependency of the `luis-apis` library) doesn't break when trying to access it to read proxy variables.
=> Fixed LUIS inspector and lingering inspector button issue

packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditor.tsx
"Read the wiki page to learn more about using ngrok and to download it."
to
"Read the wiki page to learn more about using ngrok and **how** to download it."
=> Fixed wording on settings page describing ngrok.

CHANGELOG.md
To match [4.5 release notes.](https://github.com/microsoft/BotFramework-Emulator/releases/tag/v4.5.0)
=> Added change log entry for bot state pagination.

CHANGELOG.md, packages/app/client/src/ui/editor/emulator/parts/chat/chat.spec.tsx, packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx
Fixes #1680 
===
The root cause is that when an activity is clicked on, it fires off both highlight activity & set inspector objects actions that then modify the chat document in the store.
This change in the store causes the `chat.tsx` component to re-render and the entire Web Chat control with it, which wipes the state of input fields within adaptive cards.
Preventing that re-render from happening seems like a very hard problem, if not impossible, given our current DOM structure.
The fix here is to intercept clicks & keydown events within activities, check if they originated within an input field, and prevent the highlight and select activity actions from being fired.
=> Fixed issue where adaptive card inputs were being reset.

CHANGELOG.md, packages/app/client/src/ui/editor/emulator/parts/log/logEntry.tsx, packages/app/main/src/restServer.ts
Fixes #1673 
===
HTML responses are now embedded in the `value` key of the payload under the `root` to improve readability.
Example of rendering the following error page:
```
<!DOCTYPE html>
<html>
<head>
<title>500 - Internal Server Error</title>
</head>
<body>
<p>Oops! Looks like there was an internal server error. :(</p>
</body>
</html>
```
**Before:**
**After:**
=> Fixed issue where html errors were being displayed incorrectly.

CHANGELOG.md, packages/app/client/src/ui/editor/emulator/parts/chat/chat.spec.tsx, packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx
Fixes #1680 & #1683 
===
To ensure that all Adaptive Card inputs (in Web Chat) are handled properly, I took the [sample card JSON found on the "Inputs" page in the Adaptive Cards docs](https://adaptivecards.io/samples/Inputs.html), and added logic to handle all the inputs rendered from that JSON.
The following elements should now be handled as well as all other input tag elements (date pickers, number pickers, etc):
- compact choice sets (dropdown lists)
- multiline text inputs (textarea)
- labels for choice sets and toggles (radio buttons / checkboxes)
**NOTE:** At points in the gif it looks like I'm interacting with invisible UI elements (when using the date picker / dropdown). That's because my screen recorder was unable to record floating UI elements for whatever reason.
=> Fixed click handling within all adaptive card inputs.

.gitignore, .vscode/launch.json, CHANGELOG.md, package-lock.json, package.json, packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.tsx, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.tsx, packages/app/main/e2e/createBot.spec.ts, packages/app/main/e2e/mocks/electronDialog.ts, packages/app/main/e2e/mocks/electronDialogPreload.js, packages/app/main/e2e/startup.spec.ts, packages/app/main/e2e/utils.ts, packages/app/main/package-lock.json, packages/app/main/package.json, packages/app/main/src/main.ts, packages/extensions/luis/client/package.json
Addresses #1621 
===
- Added two e2e tests and setup infrastructure
- one test verifies that the app starts up with the correct title
- the other test creates a bot via the create bot modal, and then verifies that the bot was written to disk
- e2e tests can be ran from the root of the project using `npm run test:e2e`
- added some `id` properties to HTML for easier WebDriver DOM traversing
=> Setup initial e2e tests with Spectron.

CHANGELOG.md, packages/app/main/src/commands/oauthCommands.ts
There was an issue when the Emulator would fallback to sending an emulated oauth token (in the case that we couldn't generate a sign-in link for a genuine oauth token), where the conversation id was being sent as the token instead of a token with the following format:
`emulatedToken_<GUID>`
which was being passed along from [this function call](https://github.com/microsoft/BotFramework-Emulator/blob/master/packages/app/client/src/hyperlinkHandler.ts#L76) in `hyperlinkHandler.ts`
===
**Before fix:**
**After fix:**
=> Fixed issue with emulated oauth token.

CHANGELOG.md, packages/app/main/src/ngrok.spec.ts, packages/app/main/src/ngrok.ts, packages/emulator/core/src/conversations/middleware/replyToActivity.spec.ts, packages/emulator/core/src/conversations/middleware/replyToActivity.ts
Fixes #1728 
===
Before, if the Emulator failed to spin up an ngrok instance for the OAuth signin flow (due to a misconfigured ngrok path, or some other ngrok related error), it would swallow the error and fall back to generating an emulated OAuth token.
This change will now log any errors from that flow to the log panel, and tell the user that it is falling back to generating an emulated OAuth token.
=> Added error logging to OAuth signin link generation flow.

packages/app/client/src/ui/editor/welcomePage/howToBuildABot.tsx
#1714 
The links above, 'from Azure' and 'locally' will now read "Create a bot from Azure" and "Create a bot locally" when navigating over these links in scan mode.
=> Add aria-labels to build a bot links

CHANGELOG.md, packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditor.scss, packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditor.tsx
Addresses #1768 
===
Inputs within each of the App Settings sections will now be prefaced by their respective headings when using a screen reader.
Ex: "Application Updates grouping. Automatically download and install updates checkbox unchecked."
=> Fixed input grouping semantics in app settings editor.

CHANGELOG.md, packages/app/client/src/ui/dialogs/azureLoginPromptDialog/azureLoginPromptDialog.tsx, packages/app/client/src/ui/styles/themes/dark.css, packages/app/client/src/ui/styles/themes/light.css
#1740 
Updated the link color in `botCreationDialog` and `botSettingsEditor` to be `#3062D6`, which passes Luminosity contrast ratio guidelines when on `#f4f4f4` background. The new appearance is:
Just as quick proof that this doesn't affect other links, here is a list of all instances of `--link-color`, which only occur in dialogs (where this change needs to be affected).
=> #1740 fix Luminosity on dialog link color

CHANGELOG.md, packages/app/client/src/ui/styles/themes/light.css
#1766
Disabled input contrast ratio on light theme was not high enough. This fix changes the text color of disabled inputs and labels in light mode. (Dark mode and high contrast already pass)
See below:
Got a verbal okay on this from @DesignPolice, but lmk if anyone wants to discuss this. At the moment the list of approved greys for Emulator does not have a large selection of text colors that will work with a11y on white.
=> [#1766] Increase contrast of input labels on light theme

packages/app/client/src/ui/editor/emulator/parts/chat/chat.spec.tsx, packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx, packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.spec.tsx, packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.tsx, packages/extensions/json/bf-extension.json
Solves #1699 #1694 
Allows the users to copy the activities in JSON format using the _"Copy json"_ button placed in the inspector panel or using the context menu items for the activities in the chat session. 
- Add _"Copy json"_ button
- Add test for context menu displayed for the activities in default mode
- Enable context menu for activities in default mode 
- Add test when the "Copy json" button is clicked
The next image shows how the "Copy json" button works.
Also, this one shows the context menu enabled for the activities in default mode.
=> [ISSUE#1699] Introduce a context menu -> copy JSON in the JSON inspector

CHANGELOG.md, packages/sdk/ui-react/src/layout/row/row.scss
#1742 
Fix appearance of bot creation dialog anchors, which were previously not showing the entire boxed border on focus. This fix removes `overflow:hidden` from the Row component.
This is how the the dialog looks now:
=> [#1742] Overflow visible on row to show focus borders

CHANGELOG.md, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.scss, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.scss.d.ts, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.tsx, packages/app/client/src/ui/editor/welcomePage/welcomePage.scss, packages/app/client/src/ui/styles/themes/dark.css, packages/app/client/src/ui/styles/themes/high-contrast.css, packages/app/client/src/ui/styles/themes/light.css, packages/sdk/ui-react/src/widget/autoComplete/autoComplete.spec.tsx, packages/sdk/ui-react/src/widget/autoComplete/autoComplete.tsx, packages/sdk/ui-react/src/widget/dialog/dialog.scss, packages/sdk/ui-react/src/widget/dialog/dialog.scss.d.ts, packages/sdk/ui-react/src/widget/dialog/dialog.tsx
#1723, #1725, #1726, #1727, #1729
===
Fixed the following issues within dialogs:
- the open bot dialog will no longer appear to lose focus after tabbing away from the "Browse" button
- pressing "Escape" while using the autocomplete control in the open bot dialog will no longer close the dialog
- there is now a focus indicator surrounding the close button on all dialogs
- pressing "Escape" after opening the native file browse dialog using the "Browse" button will no longer close the dialog
- fixed color contrast ratio for links within dialogs
**Close icon focus indicator:**
**"Learn more" link color contrast:**
=> [#1723, #1725, #1726, #1727, #1729] Fixed various dialog accessibility issues.

packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditor.tsx
Solves #1774 
The save button wasn't updating the `dirty` variable, so it didn't  change its state. 
- Update `dirty` on state when clicking on save button
=> [ISSUE#1774] Update dirty on state when clicking on save button 

CHANGELOG.md, packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.scss, packages/app/client/src/ui/styles/themes/dark.css, packages/app/client/src/ui/styles/themes/high-contrast.css, packages/app/client/src/ui/styles/themes/light.css, packages/sdk/ui-react/src/widget/autoComplete/autoComplete.scss
#1743 
Previously the endpoint notification text for opening a bot was showing as a low-contrast yellow. I fixed the text to a dark grey per @DesignPolice. Since the openBotDialog and botCreationDialog components were displaying different colors for these texts, I made both of them dark grey. 
High Contrast:
(And for sanity, Dark:)
=> #1743 - Fix endpoint notify text color

CHANGELOG.md, packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.scss, packages/app/client/src/ui/styles/themes/dark.css, packages/app/client/src/ui/styles/themes/high-contrast.css, packages/app/client/src/ui/styles/themes/light.css
#1754
===
**(Colors taken from VS Code color palette)**
=> [#1754] Fixed log panel timestamp color on light theme.

CHANGELOG.md, packages/app/client/src/ui/media/ic_next.svg
Solves #1815 
The luminosity ratio was less than 3:1, and it should be greater than or equal to 3:1.
- Change arrow buttons luminosity ratio using `Azure Blue - #0078D4`
=> [ISSUE#1815][MAS1.4.11] [Visual Requirements-Debug] Luminosity Ratio is less than 3:1 for “Previous and next” arrow buttons 

CHANGELOG.md, packages/app/client/src/ui/dialogs/connectServicePromptDialog/connectServicePromptDialog.tsx
#1800 
===
Some links within the service dialogs were missing text and eating focus when using keyboard navigation, which was not accessible.
**Before:**
**After:**
=> [#1800] Fixed invisible links within service dialog.

CHANGELOG.md, packages/app/client/src/ui/dialogs/resourcesSettings/resourcesSettings.tsx
#1792
Fixes #1260
===
The transcripts path input field in the resource settings dialog was not editable even though it was marked as editable. This was an accessibility issue for people using screen reader technologies as well as a bug.
There was also a bug where selecting a new transcripts path by using the browse button was not resolving the promise correctly, producing `[object object]` within the text field.
**Before:**
**After:**
=> [#1792] Fixed issue with transcripts path input.

CHANGELOG.md, packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.tsx, packages/app/client/src/ui/dialogs/botSettingsEditor/botSettingsEditor.tsx, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.tsx, packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.tsx, packages/app/client/src/ui/shell/explorer/endpointExplorer/endpointEditor/endpointEditor.tsx
#1795
===
Made links labelled "Learn more" more descriptive about what they actually point to.
=> [#1795] Fixed an accessibility issue with link descriptiveness.

CHANGELOG.md, packages/app/client/src/ui/media/ic_chevron_down.svg, packages/app/client/src/ui/shell/explorer/endpointExplorer/endpointEditor/endpointEditor.scss, packages/app/client/src/ui/shell/explorer/endpointExplorer/endpointEditor/endpointEditor.scss.d.ts, packages/app/client/src/ui/shell/explorer/endpointExplorer/endpointEditor/endpointEditor.tsx
#1796
===
The collapsible region was not reading expanded / collapsed state when using a screen reader, now it reads the state properly:
> "Azure bot service configuration button (expanded | collapsed)"
I also fixed the markup and styling.
**Before:**
**After:**
=> [#1796] Fixed accessibility issue with collapsible area in endpoint dialog.

CHANGELOG.md, packages/sdk/ui-react/src/widget/dialog/dialog.tsx
#1799
===
The narrator was reading out "Header level 2" when reading out the information for the dialog close button, but now it only reads out the information for the close button.
=> [#1799] Fixed a screen reader issue with the dialog close button.

CHANGELOG.md, package-lock.json, package.json, packages/app/client/src/ui/editor/emulator/parts/chat/chat.spec.tsx, packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx
#1753 
Previously the focus indicator on the File Upload button in chat was not showing up. This fix now shows the focus, as seen above.
=> #1753 fix focus indicator on file upload button

CHANGELOG.md, packages/app/client/src/ui/editor/emulator/parts/chat/chat.scss, packages/app/client/src/ui/styles/themes/dark.css, packages/app/client/src/ui/styles/themes/high-contrast.css, packages/app/client/src/ui/styles/themes/light.css, packages/sdk/ui-react/src/widget/splitButton/splitButton.scss
Focus color has been fixed for selected activities and the restart conversation button
=> #1757 Fix focus outline color for selected activities & restart

CHANGELOG.md, packages/app/client/src/ui/editor/welcomePage/howToBuildABot.tsx, packages/app/client/src/ui/editor/welcomePage/welcomePage.scss, packages/app/client/src/ui/editor/welcomePage/welcomePage.scss.d.ts, packages/sdk/ui-react/src/widget/smallHeader/smallHeader.tsx
#1822
===
Fixed heading HTML semantics (bumped `<h3>`'s to `<h2>`'s and changed `HOW TO BUILD A BOT` header styling to match other headers.
=> [#1822] Improved heading accessibility on welcome page.

CHANGELOG.md, packages/sdk/ui-react/src/widget/dialog/dialog.tsx
#1793
===
Dialog headings will now be properly read by screen reader technology, and navigation via browse mode should no longer become stuck.
=> [#1793] Improved dialog widget accessibility.

CHANGELOG.md, packages/app/client/src/ui/editor/emulator/logPanel/logPanel.tsx, packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.tsx, packages/app/client/src/ui/shell/main.tsx, packages/app/client/src/ui/shell/mdi/mdi.tsx
#1833 
===
Added ARIA landmarks for easier keyboard navigation.
Here's a visual representation:
If the tabs are split, the two groups will read: "primary editor region" & "secondary editor region"
=> [#1833] Added landmarks for improved keyboard navigation.

CHANGELOG.md, packages/app/client/src/ui/shell/mdi/tabBar/tabBar.spec.tsx, packages/app/client/src/ui/shell/mdi/tabBar/tabBar.tsx, packages/app/client/src/ui/shell/mdi/tabBar/tabBarContainer.ts, packages/sdk/ui-react/src/widget/dialog/dialog.scss
#1749
Due to accessibility issues, we are disabling Presentation mode temporarily instead of investing time in the fix when we are not yet decided on how to improve this feature. For more information, please see #1866 
Presentation mode is now hidden, but the related code has not been deleted.
=> [#1749] Disable presentation mode

CHANGELOG.md, packages/sdk/ui-react/src/widget/checkbox/checkbox.tsx
#1823
Checkboxes were previously reading the label twice. Adding aria-label prevents double reading of text.
=> Add aria-label to checkboxes to prevent doubling of text

packages/app/main/src/windowManager.ts
OAuth providers can use client side scripts such as JQuery during the authorize process. Electron has trouble with client side JQuery due to node extensions it adds to the window object leading to the user seeing a blank page. Since the authorize window should be treated like a normal browser, turn the node integrations off as recommended here:
https://electronjs.org/docs/faq#i-can-not-use-jqueryrequirejsmeteorangularjs-in-electron
=> Turn nodeIntegration off in OAuth windows

CONTRIBUTING.md
SO has changed the tag so I have updated the docs - See https://meta.stackoverflow.com/questions/374974/modify-botframework-tag-to-botframework-v3-or-merge-all-botframework-as-v4
=> Update Stack Overflow tag after community merged it with botframework

CHANGELOG.md, package-lock.json, packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/connectedServiceEditor.scss, packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/connectedServiceEditor.scss.d.ts, packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/connectedServiceEditor.tsx, packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/kvPair.spec.tsx, packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/kvPair.tsx
#1846 
===
The `<KvPair/>` component was actually broken and did not work. Additionally, the accessibility was not satisfactory.
Before, the control would try to auto-add new rows as you started filling in the previous rows, but did not work properly. The new, simplified approach provides buttons to add or remove rows.
The component will now also focus the newest row after adding a row, as well as announce to the screen reader when the user deletes a row.
**Before:**
**After:**
=> [#1846] Fixed functionality and a11y issues with generic service editor dialog.

CHANGELOG.md, packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.scss
=> [#1743] Fixed bot creation link color contrast.

CHANGELOG.md, packages/app/client/src/ui/a11y/ariaAlertService.spec.ts, packages/app/client/src/ui/a11y/ariaAlertService.ts, packages/app/client/src/ui/a11y/index.ts, packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.spec.tsx, packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.tsx, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.spec.tsx, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.tsx, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialogContainer.ts, packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditor.spec.tsx, packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditor.tsx, packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditorContainer.ts, packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.spec.tsx, packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.tsx, packages/app/client/src/ui/editor/emulator/parts/inspector/inspectorContainer.ts, packages/app/main/src/extensions/inspector-preload.js, packages/extensions/json/src/windowHostReceiver.tsx, packages/sdk/client/src/extensions/host.ts
#1730, #1773, #1820, #1849
===
- Added `ariaAlertService.ts` in `packages/app/client`
- creates an invisible `<span>` with `role="alert"` that will be read by any screen reader technologies and then removed after 5 seconds
- Added screen reader alerts for the following actions:
- saving app settings
- bot URL validation messages in Open Bot dialog
- hiding, showing, and copying bot secret in Create Bot dialog
- navigating to previous and next bot states in the inspector
- toggling diff mode in the inspector
- copying JSON in the inspector
- Fixed accessibility around bot secret input in Create Bot dialog
- previously, secret input was always disabled, so it was invisible to screen readers
- secret input is now read-only
- fixed label on secret input (was not being narrated before)
=> [#1730, #1773, #1820, #1849]Added screen reader alerts for various actions throughout the app.

CHANGELOG.md, packages/app/client/src/commands/uiCommands.spec.ts, packages/app/client/src/commands/uiCommands.ts, packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.spec.tsx, packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.tsx, packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialogContainer.ts, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.spec.tsx, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.tsx
#1730
===
The user will now be alerted about validation every 2 seconds at the most.
=> [#1730] Fixed endpoint validation a11y issues.

CHANGELOG.md, packages/sdk/ui-react/src/widget/textField/textField.tsx
#1772 
Minor fix to my changes where the error message "Enter a user ID" was not being read by NVDA when focused on the text field. This fix adds that message to the text field.
(no visual changes)
=> Add labelledby error message to <TextField>

CHANGELOG.md, packages/sdk/ui-react/src/widget/dialog/dialog.tsx
#1793
===
Fixes focus order of Dialog controls while in browse mode so that it is aligned with how the dialog is laid out visually.
Previous order:
**Dialog heading** -> **Close button** -> **Dialog content**
New order:
**Close button** -> **Dialog heading** -> **Dialog content**
=> [#1793] Fixed focus order a11y issue with resources dialog.

CHANGELOG.md, packages/app/client/src/ui/styles/themes/dark.css, packages/app/client/src/ui/styles/themes/high-contrast.css, packages/app/client/src/ui/styles/themes/light.css, packages/sdk/ui-react/src/widget/checkbox/checkbox.scss
#1712 
[bug]
This fixes the focus colors for the checkbox and tab's close button. 
Modifications:
- checkbox's *checked and focused* border is 2px solid #00BCF2
- checkbox's *unchecked and focused* border is 2px solid --global-focus-outline-color
- tab's close button's *focused* border is 1px solid --global-focus-outline-color
edit: 
Forgot to check the other themes. They looked alright, but in the interest of consistency and contrast, I upped both dark and high-contrast themes to 2px border focus as well. See above for screencaps.
=> Fix focus color for checkbox & tab's close button

CHANGELOG.md, packages/app/client/src/ui/editor/emulator/parts/chat/activityWrapper.spec.tsx, packages/app/client/src/ui/editor/emulator/parts/chat/activityWrapper.tsx
#1712 
Selected activities will now be noted as checked when selected, and at the same time open the activity in the json viewer.
- ActivityWrapper has been changed from button to checkbox, and tests have been updated.
=> [#1712] Update ActivityWrapper to be accessible

CHANGELOG.md, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.spec.tsx, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.tsx, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialogContainer.ts, packages/sdk/ui-react/src/widget/autoComplete/autoComplete.spec.tsx, packages/sdk/ui-react/src/widget/autoComplete/autoComplete.tsx
#1846
===
- Removed ARIA alerts for Bot URL validation
- Added functionality to `<AutoComplete />` component so that it properly narrates any error messages
=> [#1846] Fixed open bot dialog url validation a11y issue.

CHANGELOG.md, packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditor.spec.tsx, packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditor.tsx
#1773
===
After hitting the "Save" button in the App Settings Editor, the focus will now be go to the path to ngrok input field.
=> [#1773] Fixed app settings editor a11y focus issue.

CHANGELOG.md, packages/app/client/src/utils/eventHandlers.spec.ts, packages/app/client/src/utils/eventHandlers.ts
In #1893 I implemented functionality for native browser functions (cut, copy, paste, etc.) that were already functional inside of Chrome.
The implemented functionality didn't eat or stop the original event's native behavior, so actions like cut, copy, paste, were being fired twice instead of a single time. This was problematic when pasting credentials into the Open Bot dialog because they were duplicated if pasted into inputs with Ctrl+V, and thus were wrong when sent to the server.
Ex:  myPassword --> Ctrl + V --> myPasswordmyPassword
I removed my implementation and will just leave the functionality up to the browser.
=> Fixed issue with duplicate native browser functions.

CHANGELOG.md, packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.tsx, packages/app/client/src/ui/dialogs/dialogStyles.scss
#1806 
Various minor fixes
- Adds an aria-label "Bot encryption key" to the secret's textfield
- Changes placeholder text (which is read by the AT) to read "Your keys are not encrypted", `encryptKeys` boolean is true
- adds `aria-label` to the `<TextField>` component.
- Styling fixes for the Hide Secret and Copy Secret buttons, which also fixes the way the AT reads both buttons out in browse mode
=> #1806 Fix AT readout of botCreationDialog secret buttons

CHANGELOG.md, packages/app/client/src/ui/styles/themes/dark.css, packages/app/client/src/ui/styles/themes/high-contrast.css, packages/app/client/src/ui/styles/themes/light.css, packages/app/client/src/ui/styles/themes/redline.css
Applied theming to `<InsetShadow />` component to improve dark and high contrast themes.
(Light looks the same.)
**Before:**
**After:**
=> Applied theming to <InsetShadow> component.

CHANGELOG.md, packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/connectedServiceEditor.scss, packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/kvPair.tsx
#1846
===
(Includes changelog entry for Southwork's most recent PR #1923)
=> [#1846] Fixed a11y focus issue with key / value pairs in service editor.

CHANGELOG.md, packages/app/client/src/ui/styles/themes/dark.css, packages/app/client/src/ui/styles/themes/high-contrast.css, packages/app/client/src/ui/styles/themes/light.css, packages/sdk/ui-react/src/widget/button/button.scss
#1771 
This PR fixes the styling for the `<DefaultButton>` (Cancel button on dialogs) component, which previously was not high enough contrast. I got these specs from @DesignPolice, which are borrowing a bit from v.next design (Fluent) for styling / simplicity of implementation. Using colors available in `neutral.css` was complicated and started a chain reaction in color-swaps, so this is the simple alternative we went with.
Please see below for a gif overview of what the default button now looks like in all three themes. No testing added.
=> [#1771] DefaultButton a11y styling fixes

CHANGELOG.md, packages/app/client/src/commands/botCommands.spec.ts, packages/app/client/src/commands/botCommands.ts, packages/app/client/src/state/sagas/botSagas.ts, packages/app/client/src/ui/helpers/activeBotHelper.spec.ts, packages/app/client/src/ui/helpers/activeBotHelper.ts, packages/app/main/src/protocolHandler.spec.ts, packages/app/main/src/protocolHandler.ts
The `bot_open` telemetry event will now include a `source` property that will distinguish bots opened via url to bots opened via path (.bot file).
=> Added telemetry property to track bots opened via path or url

CHANGELOG.md, packages/app/main/e2e/createBot.spec.ts, packages/app/main/e2e/exportAndImportTranscript.spec.ts, packages/app/main/e2e/inspectLogItemsAndActivities.spec.ts, packages/app/main/e2e/navigateADialog.spec.ts, packages/app/main/e2e/talkToBotViaBotFile.spec.ts, packages/app/main/e2e/talkToBotViaUrl.spec.ts, packages/app/main/e2e/utils.spec.ts
On Linux, and I believe what Andy encountered on Mac as well, the tests would sometimes be prevented from functioning correctly due to a modal being shown in the app on startup that would cover the entire screen.
This PR adds a utility function to dismiss any showing dialogs before proceeding with the tests.
I also noticed that on Linux, querying an element for its `checked` attribute was returning `null` instead of `false`, like it does on Windows. The check has been changed to check for falsiness instead of the value being `=== false`.
Results:
=> Made e2e tests more reliable across different machines.

CHANGELOG.md, packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditor.tsx
=> Custom user ID validation should no longer show when disabled.

CHANGELOG.md, packages/app/client/src/state/sagas/botSagas.spec.ts, packages/app/client/src/state/sagas/botSagas.ts, packages/app/client/src/ui/shell/explorer/notificationsExplorer/notificationsExplorer.scss
Error message and status code are now surfaced in the error notification.
**Before:**
**After:**
=> Improved error logging when opening a bot via URL in debug mode

packages/app/client/src/ui/shell/explorer/endpointExplorer/endpointEditor/endpointEditor.tsx
Solves #1904
Fixes how focus goes to the text fields under _**"Azure Bot service Configuration"**_ when the dropdown is not expanded.
We added a **_tabIndex_** attribute to the TextFields under _**"Azure Bot service Configuration"**_ section. This attribute is set to -1 on rendering and changes when the on-click event is called.
Additionally, we noticed that this issue was happening on windows as well. The same solution applies to all three platforms.
In the following images, you can see how the focus goes to the TextFields only when **_"Azure Bot service Configuration"_** section is expanded:
=> [ISSUE#1904][MAS2.4.3][Focus Order - Endpoint] Focus order is not logical under "Azure bot service configuration" dropdown

packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.tsx
Solves #1910
Fixes how the focus goes to the three hidden buttons on the JSON Inspector pane.
In the **Inspector** component, we added two attributes to the _accessory buttons_ when these are disabled. These attributes are `TabIndex=-1` and `aria-hidden=true`. This way, the focus won't go to these buttons while they are disabled, only in _Debug Mode_ when they get enabled.
Additionally, we noticed that this issue was happening on windows as well. The same solution applies to the three platforms, Windows, MacOS, and Linux.
In the following images, you can see how the focus goes to the accessory buttons only in Debug Mode when they are enabled:
=> [ISSUE#1910][MAS4.2.10][Focus Order - Connect the bot] In JSON tab, the focus goes on the hidden controls

CHANGELOG.md, packages/app/client/src/ui/editor/markdownPage/markdownPage.scss
=> Fixed link color contrast on debug docs page.

CHANGELOG.md, packages/app/client/src/ui/styles/themes/dark.css, packages/app/client/src/ui/styles/themes/high-contrast.css, packages/app/client/src/ui/styles/themes/light.css, packages/sdk/ui-react/src/widget/splitButton/splitButtonPanel/splitButtonPanel.scss, packages/sdk/ui-react/src/widget/splitButton/splitButtonPanel/splitButtonPanel.tsx
#1912
===
Fixes HC theming for the split button panel, as well as improves focus indication inside the panel when using Dark / Light themes (added teal border).
**Before:**
**After:**
=> Improved focus indication in split button panel.

CHANGELOG.md, packages/app/client/src/ui/shell/explorer/endpointExplorer/endpointEditor/endpointEditor.tsx
Solves #1904
Fixes the VO navigation when the Azure Bot Service Configuration is collapsed.
We added an `aria-hidden` attribute to the `abs-config-content` component that will be true or false if the content is collapsed or expanded.
=> [ISSUE#1904][MAS2.4.3] [Focus Order - Endpoint] Focus order is not logical under "Azure bot service configuration" dropdown.

CHANGELOG.md, packages/app/client/src/state/actions/connectedServiceActions.spec.ts, packages/app/client/src/state/actions/connectedServiceActions.ts, packages/app/client/src/state/sagas/servicesExplorerSagas.spec.ts, packages/app/client/src/state/sagas/servicesExplorerSagas.ts, packages/app/client/src/ui/shell/explorer/servicePane/servicePane.spec.tsx, packages/app/client/src/ui/shell/explorer/servicePane/servicePane.tsx, packages/app/client/src/ui/shell/explorer/servicesExplorer/servicesExplorer.spec.tsx, packages/app/client/src/ui/shell/explorer/servicesExplorer/servicesExplorer.tsx, packages/app/client/src/ui/shell/explorer/servicesExplorer/servicesExplorerContainer.ts, packages/app/main/src/commands/electronCommands.spec.ts, packages/app/main/src/commands/electronCommands.ts, packages/app/main/src/services/contextMenuService.spec.ts, packages/app/main/src/services/contextMenuService.ts, packages/app/main/src/state/actions/connectedServiceActions.spec.ts, packages/app/main/src/state/actions/connectedServiceActions.ts, packages/app/shared/src/types/contextMenuCoordinates.ts
#1907
===
The add and sort service pane buttons spawn a context menu. The old behavior spawned the menu at the cursors' current position (Electron's default). Now, the context menu is spawned directly under the triggering button.
**Before:**
**After:**
=> [#1907] Add / sort service menus now show under trigger buttons.

CHANGELOG.md, packages/app/client/src/ui/dialogs/botSettingsEditor/botSettingsEditor.tsx, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.tsx, packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.tsx, packages/app/client/src/ui/shell/explorer/endpointExplorer/endpointEditor/endpointEditor.tsx, packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/kvPair.tsx
=> [#1915] Fixed a11y issue with link descriptiveness.

CHANGELOG.md, packages/app/main/src/ngrok.ts
Carrying over the fix for an issue that users were experiencing when trying to connect to remote bots on slower networks.
===
Users on faster networks should not notice any change, and users on slower networks should no longer be broken / intermittently broken.
=> Increased ngrok spawn timeout to 15 seconds.

CHANGELOG.md, packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/connectedServiceEditor.spec.tsx, packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/connectedServiceEditor.tsx
#1906 
===
There was a bug in the `ConnectedServiceEditor` code that was causing `botframework-config` to throw, which then broke the saga that originally opened the add service context menu. This subsequently broke all future interactions with the service sagas, preventing the context menu or service buttons from working anymore.
I added code to initialize the QnA Maker service editor with a sample host name to satisfy `botframework-config` and prevent the error from being thrown.
There was also another bug where the `learnMoreLinkButton` function was being called like a getter even though it was a function, and so none of the service editors were actually rendering the learn more links, which is now fixed.
=> [#1906] Fixed bugs within connected service editor.

packages/app/main/src/commands/emulatorCommands.spec.ts, packages/app/main/src/server/state/conversation.ts
Fixes: https://github.com/microsoft/botbuilder-dotnet/issues/2690
This has also been addressed in the sdks:
[dotnet](https://github.com/microsoft/botbuilder-dotnet/pull/3012)
[javascript](https://github.com/microsoft/botbuilder-js/commit/cdb8d6f0123175f526d935fefcac5db2b188d9aa#diff-cee27df6126434892e9a6747003fb69eR455)
=> Always generate an activity id, ignoring received ids

CHANGELOG.md, packages/sdk/ui-react/src/widget/button/linkButton.tsx, packages/sdk/ui-react/src/widget/button/primaryButton.tsx
Solves #1890
With these changes, the PrimaryButton and LinkButton elements will be hidden to screen readers while disabled.
In the issue report, the tester says the disabled buttons close the dialogs when pressing space, this happens because the Voiceover navigation mode goes through the elements even if they are not focusable by the keyboard, so the keyboard only follows it when it lands in a focusable element, and as a disabled button is not focusable, the keyboard focus remains in the last focusable element, in the case shown by the tester is the cancel button, so when pressing space bar or enter, the cancel button is clicked. This won't keep happening as **Voiceover** can't navigate to the Connect button when it is disabled
We added an attribute of `aria-hidden='true'` to the …
=> [ISSUE#1890][Functional - Open Bot Dialog] The focus goes on the disabled controls and functioning by space/return.

CHANGELOG.md, packages/sdk/ui-react/src/widget/collapsibleJsonViewer/collapsibleJsonViewer.tsx
#1913
===
The root node `<ul>` of the collapsible JSON viewer component was being assigned a `tabindex` of `0`, which was making the root of the tree focusable which was unnecessary. On Mac, this would read as "Empty table," which is not useful information for users relying on a screen reader.
I have removed this attribute from the root node, and the component remains keyboard accessible without relaying any irrelevant information.
(Tested on Windows as well, and a11y remains the same.)
**Before:**
**After:**
=> [#1913] Fixed a11y issue with json viewer component.

CHANGELOG.md, packages/sdk/ui-react/src/widget/checkbox/checkbox.tsx
#1905 
===
Made minor changes to the `<Checkbox />` component DOM structure.
The previous structure wrapped the `<input>` in a `<label>` element, and also attached an `aria-label` attribute to the input. This caused screen readers to narrate both the `aria-label` and the text within the `label` element.
I have changed the outer element to be a `<div>` with a `role` or `"presentation"` so that the screen reader ignores it, and I've wrapped the inner label text in a `<label>` tag so that the component follows the standard semantic structure of a labelled checkbox input. I've also removed the `aria-label` attribute from the `<input>` element, because the screen reader should know that the `<label>` tag describes the `<input>`.
I've tested this on both Windows, and Mac, and they read …
=> [#1905] Fixed a11y issue with narration of checkboxes.

packages/sdk/ui-react/src/widget/textField/textField.tsx
Fixes #1911
This pull request fixes how the Voiceover reads the error label in _TextField_ components,
Updated the _TextField_ component to use an `aria-label` instead of an `aria-describedby` attribute. This way we can create a label with the combination of the component label and the error message.
=> [ISSUE#1911][MAS1.3.1][Screen Reader-Add other service] After error, the voiceover announced incorrect label of the edit fields.

CHANGELOG.md, packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/connectedServiceEditor.scss, packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/connectedServiceEditor.scss.d.ts, packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/kvPair.spec.tsx, packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/kvPair.tsx
Solves #1908
This pull request fixes the navigation with **Voiceover** through the key-value pair text fields in the _Add other service ..._ dialog.
Now voiceover goes from the label `key` to its text field, then to the `value` label and then to its text field.
We moved the labels used for the titles inside the first _TextField_ element of the pairs, this way the label is associated with the input field it corresponds.
Also, we changed how the key-value pairs are displayed in the dialog, replacing a list for a table using rows as the tester suggested.
Finally, we made some changes to the styling to have the same visual representation as before. For this, we moved some style properties inside a new class to be used for the rows.
In the following recording, you can see **Voiceover** …
=> [ISSUE#1908][MAS4.2.10][Focus Order - Add other service] With voiceover consolidated focus goes on "Key and Value".

CHANGELOG.md, packages/app/client/src/ui/styles/themes/light.css
#1964
===
- The user id disabled label text was fixed in a previous PR, and is now `#666` which achieves a color contrast ratio of 5.7:1.
- The Web Chat timestamps have been changed to this color as well.
=> [#1964] Fixed color contrast issue w/ WC timestamps on light theme.

CHANGELOG.md, packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.scss, packages/app/client/src/ui/shell/explorer/botNotOpenExplorer/botNotOpenExplorer.scss, packages/app/client/src/ui/shell/explorer/resourceExplorer/resourceExplorer.scss, packages/app/client/src/ui/shell/explorer/servicesExplorer/servicesExplorer.scss, packages/app/client/src/ui/styles/themes/dark.css, packages/app/client/src/ui/styles/themes/high-contrast.css, packages/app/client/src/ui/styles/themes/light.css
#1976
===
- Previous / next diff buttons in bot state inspector are now theme-able
- Also fixed a regression with link color contrast in explorer panels and welcome page for dark theme
**Light:**
**Dark:**
**HC:**
=> [#1976] Fixed color contrast issues with links and prev/next diff buttons.

CHANGELOG.md, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.tsx
=> [#1955] Fixed duplicate placeholder text for bot url field in open bot dialog.

CHANGELOG.md, packages/app/client/src/ui/styles/themes/light.css
#1962
===
- Web chat send buttons (upload attachment, send arrow, mic) are now darker on Light theme
=> [#1962] Fixed color contrast issue with WC send box on Light theme.

CHANGELOG.md, packages/app/client/src/ui/shell/main.tsx, packages/app/main/src/appMenuBuilder.spec.ts, packages/app/main/src/appMenuBuilder.ts, packages/app/shared/src/utils.spec.ts, packages/app/shared/src/utils.ts
#1979
===
~~**DO NOT MERGE UNTIL #2015 IS MERGED**~~ Good to merge now 👍 
Switched from native application menu to HTML-based application menu on Linux for keyboard accessibility.
Due to a bug in Electron, disabling the native menu doesn't work like it does in Windows, and so there is an empty space at the top of application window where the menu would usually be. This is a small side effect.
https://github.com/electron/electron/issues/16521
=> [#1979] Enabled HTML-based app menu for Linux.

CHANGELOG.md, packages/app/client/src/utils/eventHandlers.spec.ts, packages/app/client/src/utils/eventHandlers.ts
#1979
===
- Actually fixing it this time 😅
- When the tab focus logic was running it was only looking inside the nav bar for the first focusable element, when it actually needs to look in the app menu on Linux
Video of it working:
[linux-tab-nav.zip](https://github.com/microsoft/BotFramework-Emulator/files/3947592/linux-tab-nav.zip)
=> [#1979] Fixed app menu tab navigation issue on Linux.

CHANGELOG.md, packages/app/client/src/state/reducers/explorer.ts, packages/app/main/src/state/reducers/explorer.ts
=> Hid services pane by default.

CHANGELOG.md, packages/app/client/src/constants.ts, packages/app/client/src/state/sagas/servicesExplorerSagas.ts, packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/connectedServiceEditor.tsx
Fixes #1875
===
- After signing into Azure, trying to add a QnA maker KB would cause the in-memory QnA maker service to be initialized with a blank hostname, which was causing `msbot` to throw and crash the app
=> Fixed an issue with adding a QnA KB.

CHANGELOG.md, packages/app/client/src/ui/shell/appMenu/appMenu.spec.tsx, packages/app/client/src/ui/shell/appMenu/appMenu.tsx
=> Fixed an issue where the themes menu was empty on Windows & Linux

CHANGELOG.md, packages/app/client/src/state/sagas/azureAuthSaga.spec.ts, packages/app/client/src/state/sagas/azureAuthSaga.ts, packages/app/client/src/state/sagas/botSagas.ts, packages/app/client/src/state/sagas/frameworkSettingsSagas.spec.ts, packages/app/client/src/state/sagas/frameworkSettingsSagas.ts, packages/app/client/src/utils/getSettingsDelta.spec.ts, packages/app/client/src/utils/getSettingsDelta.ts, packages/app/main/src/commands/ngrokCommands.ts, packages/app/main/src/server/routes/emulator/handlers/sendTokenResponse.spec.ts, packages/app/main/src/server/routes/emulator/handlers/sendTokenResponse.ts, packages/app/main/src/state/sagas/settingsSagas.ts, packages/app/main/src/telemetry/telemetryService.spec.ts, packages/app/main/src/telemetry/telemetryService.ts
Fixes #2035 
===
- Added `toolName: 'bf-emulator'` to all outgoing events so that we can filter them out from other tools (bf-cli) that use the same Azure Application Insights instance
- removed `livechat_openRemote` event and added `livechat_open` which tracks both local and remote URLs being opened
- added tracking for whether a livechat opened is for gov cloud or not
- added tracking for whether a livechat opened is in debug mode or not
- consolidated Azure signin events (`signIn_success` and `signIn_failure`) into one event (`azure_signIn`) that now tracks `success` and `persistLogin` 
- added an event (`ngrok_reconnect`) for when the user reconnects to ngrok 
- added an event (`app_changeSetting`) that tracks whenever a single or multiple app settings are changed at one time
- added …
=> Added new telemetry events and properties.

packages/extensions/luis/client/src/App.tsx
Fixes #1788 
The error message now shows when using a Bot file and not when connecting to a bot through a URL
=> Resolved lUIS error from not showing up on URL based bots

CHANGELOG.md, packages/app/client/src/state/utils/throwErrorFromResponse.ts
This will help debug issues like #2086 
===
Due to the way sagas work, the errors thrown in our nested sagas are seen as uncaught and redux saga hides most of the internal properties of the thrown error and just shows the `message`, which isn't very helpful.
`redux-saga` provides an `onError` hook that you can use for catching these errors at the root level, but the `onError` will only get called if the caught error is of type `Error`. Since we defined our own error type `ResponseError` the `onError` hook never gets called. We need to update to `redux-saga@1.0.0` for that check to be fixed, but this might incur some other breaking changes that I don't think this PR should deal with. [See this issue for reference.](https://github.com/redux-saga/redux-saga/issues/1308)
For now, we will …
=> Thrown errors in client sagas are now logged to console.

CHANGELOG.md, packages/app/client/src/ui/editor/emulator/parts/chat/chat.scss, packages/app/client/src/ui/editor/emulator/parts/chat/chat.scss.d.ts, packages/app/client/src/ui/editor/emulator/parts/chat/chat.spec.tsx, packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx
Fixes https://github.com/microsoft/BotFramework-Emulator/issues/2071
Handling upload, download attachment styles of webchat from inside the emulator. These changes will be visible only after Webchat is bumped to 4.8.
=> Attachments background and fonts handled when WC will be bumped to 4.8

CHANGELOG.md, packages/app/client/src/ui/editor/recentBotsList/recentBotsList.tsx
#2052
===
Screen reader now reads the "X" button in the recent bots list as "Remove bot button"
=> [#2052] Fixed an accessibility issue with the recent bots list remove button

CHANGELOG.md, packages/app/client/src/ui/shell/appMenu/appMenu.spec.tsx, packages/app/client/src/ui/shell/appMenu/appMenu.tsx
There was a small bug in the File menu on Windows & Linux due to the addition of the Ngrok Debugger menu item. The PR #2032 that added that menu item added 2 new menu items, (the menu item itself and the separator), but the sign in and close tab menu items never had their indices adjusted to compensate for it.
So the "Close tab" menu item was being overwritten by the sign in item.
**Before fix:**
**After fix:**
=> Fixed missing item in File menu on Win / Lin.

CHANGELOG.md, package-lock.json, packages/app/main/package.json
=> Bump version to 4.8.0

CHANGELOG.md, package-lock.json, packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx, packages/app/client/src/ui/editor/emulator/parts/chat/outerActivityWrapper.spec.tsx, packages/app/client/src/ui/editor/emulator/parts/chat/outerActivityWrapper.tsx, packages/app/client/src/ui/editor/emulator/parts/chat/outerActivityWrapperContainer.ts
This PR 
- Updates the package-lock files for Emulator patch version 4.8.1
- Fixes a bug with restart conversation from activity that existed in 4.8.0. The issue being changes to restart status where not passed down from `<Chat>` to `<OuterActivityWrapper>`. Hence made use of `<OuterActivityWrapperContainer> `to funnel `restartStatus` and `mode` from `state.chats[documentId]` into activityWrapper which is a component supplied as middleware to Webchat for rendering an activity
=> Prevent passing props to activity middleware

CHANGELOG.md, packages/app/client/src/ui/editor/emulator/parts/chat/outerActivityWrapper.spec.tsx, packages/app/client/src/ui/editor/emulator/parts/chat/outerActivityWrapper.tsx, packages/app/client/src/ui/editor/emulator/parts/chat/outerActivityWrapperContainer.ts
This PR ensures "Restart Conversation from here" bubble does not appear for DL Speech bots. This functionality is not available for DL speech bots yet.
=> Added tests to ensure restart bubble not present

CHANGELOG.md, packages/app/client/src/state/sagas/botSagas.spec.ts, packages/app/client/src/state/sagas/botSagas.ts, packages/app/client/src/state/sagas/chatSagas.spec.ts, packages/app/client/src/state/sagas/chatSagas.ts
#2106
===
Fixed some faulty logic that was not behaving as expected.
The `select()` effect from `redux-saga` returns an object, so it is always truthy no matter what and will resolve to the yielded value.
Ex:
```
const val = yield select(() => false) || 'some other value';
console.log(val);  // false
```
So even when the custom user ID was set to the empty string, the start conversation logic was always initializing the conversation with the blank ID rather than defaulting to a freshly generated GUID.
=> Fixed a bug that was causing a blank User 'id' field.

CHANGELOG.md, packages/app/main/src/ngrokService.spec.ts, packages/app/main/src/ngrokService.ts
This PR makes sure the following condition holds
-  If RunNgrokOnStartup = true always use ngrok irrespective of local or remote bot
- If RunNgrokOnStartup = false; BypassNgrokOnLocalhost = true then
Local Bot - Does not use Ngrok
Remote Bot - Uses Ngrok
- If RunNgrokOnStartup = false; BypassNgrokOnLocalhost = false then
Local Bot - Uses Ngrok if configured or else returns the localhost url
Remote Bot - Uses Ngrok
=> Ngrok Startup Options

CHANGELOG.md, packages/app/main/src/ngrokService.ts
This PR makes sure Ngrok reporter reports accurately when Ngrok is used or not
=> Ngrok reporting made accurate

packages/app/main/src/server/routes/channel/conversations/handlers/createConversation.spec.ts, packages/app/main/src/server/routes/channel/conversations/handlers/createConversation.ts
Signed-off-by: Srinaath Ravichandran <srravich@microsoft.com>
Fixes the first bullet in https://github.com/microsoft/BotFramework-Emulator/issues/2097
This PR is additive. It adds the field Id to the conversation object along with conversationId which already exists in the object
=> Add id for conversation object

CHANGELOG.md, packages/app/client/src/state/sagas/servicesExplorerSagas.spec.ts, packages/app/client/src/state/sagas/servicesExplorerSagas.ts, packages/app/client/src/ui/dialogs/getStartedWithCSDialog/getStartedWithCSDialog.tsx
Noticed some issues with the Cosmos DB service dialog when running through the release checklist.
This PR fixes the following issues:
- missing dialog header
- missing "Go to <service name>" button text
- missing "Go to <service name>" button link (now links to https://azure.microsoft.com/services/cosmos-db/)
**Before:**
**After:**
=> Fixed content of signed in view of Cosmos DB service dialog.

CHANGELOG.md, CONTRIBUTING.md
Closes #1974
===
Removed some outdated information in the `CONTRIBUTING.md` doc and also added some important information about required Node versions.
=> Updated global dependency info in CONTRIBUTING.md

packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.tsx, packages/app/main/src/extensions/inspector-preload.js, packages/extensions/luis/client/src/App.tsx, packages/sdk/client/src/extensions/host.ts, packages/sdk/shared/src/types/ipc/extensionChannel.ts
This PR makes sure that when clicking on a LUIS trace while working on a bot file does not show the invalid subscription key message as a logger error instead shows it as a logger warn message. This is a temporary design fix we are making.
Fixes #2152
=> Fix: Warning message shown when clicking on LUIS trace

README.md
The repository at Microsoft Bot Framework - https://github.com/Microsoft/botframework has been marked as archived and all information has been moved to Bot Framework SDK - https://github.com/Microsoft/BotBuilder which is already in the list.
=> Remove outdated Related Link

CHANGELOG.md, packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx
The `webchat` middleware 4.10.0 returns false for `conversationUpdate, invoke` events. This PR makes sure it returns true before we render the results
=> Handle change to middleware

.vscode/launch.json, CHANGELOG.md, packages/app/client/src/state/sagas/botSagas.ts, packages/app/client/src/state/sagas/chatSagas.spec.ts, packages/app/client/src/state/sagas/chatSagas.ts, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.tsx, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialogContainer.ts, packages/app/shared/src/state/reducers/chat.ts, packages/sdk/shared/src/types/activity/startConversationParams.ts
Satisfies the P0 requirements of #2181
=> Added support for setting `randomSeed` & `randomValue` properties for transcript testing

packages/app/main/src/ngrok.ts
This PR
1.  Increases the time to wait for the ngrok process before reporting an unsuccesful ngrok spawn operation
2.  Binding the `this` context on process exit. Currently. on process exit emulator does not cleanup ngrok process that was spawned  
@garypretty
=> Increased wait time to 40seconds to spin ngrok process

README.md
Replace https://github.com/microsoft/botframework with
https://github.com/microsoft/botframework-sdk at README.md
since /botframework is deprecated (moved)
=> Update link to 'bot framework SDK' at README.md

CHANGELOG.md, packages/app/main/src/commands/electronCommands.spec.ts, packages/app/main/src/commands/electronCommands.ts, packages/app/main/src/utils/showOpenDialog.spec.ts
After bumping Electron from 4 to 11 we forgot to update our utility function that wraps the `dialog.showOpenDialog` API to return the correct value. This was causing any type of action that was using a native "Open file" dialog to silently fail -- opening a bot, transcript, etc.
[Here is the old documentation that shows the return value of v4.x's `showOpenDialog`](https://github.com/electron/electron/blob/v4.1.1/docs/api/dialog.md#dialogshowopendialogbrowserwindow-options-callback) -- it was an array of strings.
[The updated API from v11.x](https://www.electronjs.org/docs/api/dialog#dialogshowopendialogbrowserwindow-options) returns an object with a `filePaths` array containing the information that the 4.x version returned.
[CI build running …
=> Fixed opening files via electron's dialog API

CHANGELOG.md, packages/app/main/src/services/contextMenuService.ts
The `showMenuAndWaitForInput()` function was returning the entire `Electron.MenuItem` which contains functions as part of the object (click handler, etc.).
With Electron 11, these cannot be sent over IPC back to the client side because functions cannot be serialized. This was causing the result to never make it back to the client side and for the context menu action to silently fail.
I changed the API to return an object containing solely the `id` property of the selected menu item because all of the consumers of this API only care about the `id` property anyways.
[CI running here](https://fuselabs.visualstudio.com/BotFramework-Emulator/_build/results?buildId=219628&view=results)
=> Fixed a bug that was causing Electron's context menu to fail

CHANGELOG.md, packages/sdk/ui-react/src/widget/splitButton/splitButton.scss
Fixed a styling issue with the alignment of the caret icon within the `<SplitButton />` widget.
**BEFORE:**
**AFTER:**
=> Fixed split button caret icon alignment

CHANGELOG.md, packages/app/client/src/state/middleware/forwardToMain.spec.ts, packages/app/client/src/state/middleware/forwardToMain.ts
When connecting to a Direct Line Speech enabled bot, the Web Chat speech adapter object embedded in one of the redux payloads contained a circular JSON structure -- `privReco` property -- that was causing the `JSON.stringify()` call in `forwardToMain.ts` to fail.
This was ultimately causing the Redux action to fail, which resulted in an `undefined` speech adapter object being sent to Web Chat.  Web Chat could not complete the connection to the DL Speech channel.
---
This PR adds error handling for this specific case, and will bypass forwarding the speech adapters update action over to the main process of the app. It is not needed in the main process's state store anyways.
All other errors will be thrown like normal.
As an example, here's what the error message looked like:
```
Converting …
```
=> Added circular JSON handling to forwardToMain

CHANGELOG.md, packages/app/main/src/services/azureAuthWorkflowService.spec.ts, packages/app/main/src/services/azureAuthWorkflowService.ts
Previously, the Azure login flow was listening for redirects in the auth popup window using the `history` property on Electron's `BrowserWindow.webContents` property. However, [I failed to find this property documented anywhere in their current docs](https://www.electronjs.org/docs/api/web-contents#instance-properties) or even [the older docs of the version we were using.](https://github.com/electron/electron/blob/v4.1.1/docs/api/web-contents.md)
With the newer version of Electron, this `history` property was always showing up as an empty array, so the Emulator never detected that the login flow completed and reached the desired redirect URL.
I have updated the login flow to use a simpler API.
Fixes #2247
=> Updated Azure login redirect flow

packages/app/main/src/main.ts
Fixes an issue where deep linking was not working on Mac if the app was not running.
=> fix: immediately register open-url handler

CHANGELOG.md, packages/app/client/src/ui/dialogs/customActivityEditor/customActivityEditor.tsx
Fixes #2249
===
There was a bug where re-opening the custom activity editor after previously modifying the editor content would still send the default model content of "Hello world!" instead of the currently displayed content.
This PR fixes that by making sure to send the model's content back through correct event handlers when rendered, which then triggers the true value of the editor to be saved in the React component's state. The updated content is then always sent to the bot.
=> Custom activity editor now properly sends leftover content

packages/app/main/src/server/routes/directLine/handlers/upload.ts
Currently, Emulator does not return the activity id in the POST response after a file has been uploaded. Additionally, the send status hangs showing 'Sending' before timing out resulting in 'Send failed. Retry.'
Returning the correct source for the activity id value corrects the POST response. Including the `sendToSubscribers()` method addresses the send status and, further, allows the file to be downloaded.
=> Fixes activity id returned in direct line POST response and web chat send status

packages/app/client/src/ui/shell/appMenu/appMenuTemplate.ts, packages/app/client/src/utils/eventHandlers.spec.ts, packages/app/client/src/utils/eventHandlers.ts
If 'Zoom in, Zoom out' control of the 'View' menu is not performing any action when activated with the keyboard or mouse, the user will not be able to utilize the functionality available with that control. The user will face issues in navigation and will not be able to access and activated the mentioned controls.
'Zoom in, Zoom out' options in the 'View' menu are not performing any action when activated with the keyboard or mouse.
'Zoom in, Zoom out' options in the 'View' menu should be performing proper action when activated with the keyboard or mouse.
3. Navigate on the welcome screen and select Create a New …
=> [Accessibility] [Functional] Fix zoom in and zoom out features in Emulator

packages/app/client/src/ui/editor/ngrokDebugger/ngrokDebugger.tsx
If an Improper heading label is defined on the 'Ngrok status' screen for 'Tunnel Health' and 'Tunnel Status' texts, the user will get disoriented while navigating in heading mode. The h1 heading will be announced after the h2 heading which is not correct.
Improper heading structure is defined on the 'Ngrok status' screen for 'Tunnel Health' and 'Tunnel Status' texts.
Proper heading structure should be defined on the 'Ngrok status' screen for 'Tunnel Health' and 'Tunnel Status' texts.
4. The new BOT Configuration dialog opens.
5. …
=> [Accessibility] [Screen Reader] Fix improper heading level on 'Ngrok status' screen

packages/app/client/src/ui/shell/appMenu/appMenu.tsx
If no information regarding the selected theme and screen change is announced when any theme is selected and the screen adopts it, the AT user will not able to know whether the screen is changed as per the selected theme or not. The user will face issues in the utilization of the theme feature.
No information regarding the selected theme and screen change is announced when any theme is selected and the screen adopts it.
Proper information regarding the selected theme and the screen change should be announced when any theme is selected and screen adopts it.
3. Navigate on the welcome screen and select Create a …
=> [Accessibility] [Screen Reader] Add an audio alert when the user change the theme

packages/app/client/src/ui/shell/explorer/servicePane/servicePane.tsx, packages/app/client/src/ui/shell/explorer/servicesExplorer/servicesExplorer.tsx
If the Screen reader is not reading the sorting information after selecting Sorting controls present on Bot Explorer Pane, it would be difficult for screen reader users to find out if the sorting action is done or not.
The screen reader is not reading the sorting information after selecting the Sorting controls present on Bot Explorer Pane.
The screen reader should be reading the sorting information after selecting the Sorting controls present on Bot Explorer Pane. It should read as 'Sorted by Name/Type'.
4. The new BOT …
=> [Accessibility] [Screen Reader] Fix screen reader announcement after selecting sorting controls

packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.tsx, packages/app/client/src/ui/dialogs/botSettingsEditor/botSettingsEditor.tsx
If the screen reader remains silent when the focus is on the 'Hide' button present under 'setting dialog', so it would be difficult and confusing for screen reader users to find out the control.
In scan mode, narrator remains silent when the focus is on the 'Hide' button under the setting dialog.
In scan mode, narrator should announce as 'button hide' when the focus is on the 'Hide' button under the setting dialog.
4. The new BOT Configuration dialog opens.
5. Navigate on the dialog and enter inputs in edit fields then select …
=> [Accessibility] [Screen Reader] Fix hide button focus when using Narrator in botSettingsEditor and botCreationDialog

packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.tsx
If an incorrect minimum and maximum value are announced for the 'Test Options' spinner control available on the 'Open a Bot' pop-up, the user will not get correct information about the minimum and maximum values. The user will face issues in entering the values inside spinner control.
Incorrect minimum and maximum values are announced for the 'Test Options' spinner control available on the 'Open a Bot' pop-up. Minimum and maximum values are announced as zero.
Correct minimum and maximum values should be announced for the 'Test Options' spinner control available on the 'Open a Bot' pop-up.
3. Navigate on the …
=> [Accessibility] [Screen Reader] Enable the screen reader to announce maximum and minimum values for numeric input boxes

CHANGELOG.md, packages/app/main/src/server/routes/channel/conversations/handlers/replyToActivity.spec.ts, packages/app/main/src/server/routes/channel/conversations/handlers/replyToActivity.ts
There was a misplaced `next()` call in the `replyToActivity.ts` handler that is responsible for posting messages from the bot back to Web Chat. This `next()` call was terminating the response earlier than the call to `res.send(HttpStatus.OK, { id: activity.id });` on line 62 which was causing the newer version of NodeJS to throw when it was not before on the older version.
=> Moved next() in handler to fix early HTTP response termination.

CHANGELOG.md, packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.tsx
…lectron 13
In Electron 13, the default for `contextIsolation` was set to `true` when it used to be `false`.
We tried to change the default for all instances of new browser windows in https://github.com/microsoft/BotFramework-Emulator/pull/2318, but missed the `<webview>` tag for inspectors. This was causing the inspectors to be cut off from any data passed from the host (Emulator client) resulting in a blank view.
=> Fixed blank inspectors due to new contextIsolation default value

packages/app/client/src/ui/editor/recentBotsList/recentBotsList.tsx
If Screen reader users navigate on the Welcome screen and screen reader focus moves on the first bot item element, list 1 is announced with the same control. It would be confusing for screen reader users to know which list 1 is available with control.
When the focus moves on the first item element, list 1 is announced with the same control.
The screen reader announces list 1 with most of the control on the application.
When the focus moves on the first item element, the screen reader should not announce list 1 with the same control.
Because it’s confusing for users to know which list 1 is available.
3. …
=> [Accessibility] [Screen Reader] Fix screen reader announcement when navigating through "My bots" list

packages/app/client/src/ui/editor/emulator/parts/chat/chat.scss
If Keyboard users navigate on Chat with BOT screen and focus indicator is not visible properly on chat section control for upload, chat edit field, and send control then it would be difficult for users to understand focus position and users unable to get complete their task.
When the user navigates on Chat with Bot screen and focuses moves on chat section, Upload, chat edit field, and send control, visually focus indicator is not visible properly on that control, and get confused to know focus indicator position.
When the user navigates on Chat with Bot screen and focuses moves on chat section, Upload, chat edit field, and send control, visually focus indicator should be visible properly on that control, So that would not get confused to know …
=> [Accessibility] [Visual Requirement] Fix focus indicator on some controls in the Live Chat panel

packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.tsx
If users navigate on New Bot Configuration Dialog and focus move on the hide button and screen reader announce list with it, then it would be difficult for users to understand which list item is available with the hide button.
When the user navigates on New Bot Configuration Dialog and focus moves on the hide button, the screen reader announces list with it and it confusing for users which list is available with the hide button.
When the user navigates on New Bot Configuration Dialog and the focus moves on the hide button, list should not be announced with the hide button, so that the user would not get confused.
2. Bot Framework Emulator Application with Welcome screen …
=> [Accessibility] [Keyboard Navigation] Fix screen reader announcement when navigating through the Hide and Copy buttons

packages/sdk/ui-react/src/widget/textField/textField.tsx
If users navigate on New Bot Configuration Dialog and the focus moves on required edit field and screen reader invalid announce with required edit field, then it would be difficult for users to understand which invalid data entered and what is invalid on edit field.
When the user navigates on New Bot Configuration Dialog and the focus moves on required field and screen reader announces invalid required edit field and it confusing for users which invalid data entered on required edit field.
When the user navigates on New Bot Configuration Dialog and the focus moves on required field, screen reader should not announce invalid with required edit field, so that the user would not get confused.
1. Open Bot Framework Emulator …
=> [Accessibility] [Screen Reader] Fix the screen reader announcement for required edit fields

packages/app/client/src/ui/editor/ngrokDebugger/ngrokDebugger.tsx
If users navigate on the setting screen and select NGROK status viewer, the control focus indicator gets hidden, it does not land on the first interactive control on the screen and it would be confusing for users where focus indicator gets land and what is focus indicator position.
If users navigate on the setting screen and select NGROK status viewer the focus indicator gets hidden, it does not land on the first interactive control on the screen.
If users navigate on the setting screen and select NGROK status viewer the focus indicator should not get hidden, it should be land on the first interactive control on the screen.
2. Bot Framework Emulator Application with Welcome …
=> [Accessibility] [Screen Reader] Fix the focus when opening the 'Ngrok status viewer' tab

packages/app/client/src/ui/editor/emulator/emulator.spec.tsx, packages/app/client/src/ui/editor/emulator/emulator.tsx, packages/app/client/src/ui/shell/mdi/tab/tab.tsx, packages/sdk/ui-react/src/widget/splitButton/splitButton.tsx
If Keyboard users navigate on Open Bot dialog and enter field details and select save and connect control, Chat with BOT screen appear but the focus indicator does not land on the Live chat tab, it's land on restart conversation control, so it would be confusing and users would be unable to know which tab appears.
After selecting the Save button and the Live Chat tab appears, the keyboard focus indicator land on restart conversation control rather than the Live chat Tab, it would be confusing for users which tab appears.
After selecting the Save button anad the Live Chat tab appears, the keyboard focus indicator should land on the Live Chat Tab rather than restart conversation control, so that users easily know which tab appears.
**Repro …
=> [Accessibility] [Keyboard Navigation] Fix focus on the Live Chat tab

packages/app/client/src/ui/editor/emulator/emulator.spec.tsx, packages/app/client/src/ui/editor/emulator/emulator.tsx, packages/app/client/src/ui/editor/emulator/emulatorContainer.ts, packages/app/main/src/commands/emulatorCommands.ts
If users navigate on Chat with Bot screen and select save transcript and transcript get saved, but screen reader does not announce saved information also message does not appear as a saved, so it would be difficult for users to know transcript get saved or not.
After selection of Save transcript, transcript gets saved but screen reader does not announce that saved confirmation also saved message does not appear on the screen and it would difficult for users to know transcript get saved or not.
After selection of Save transcript, transcript gets saved, So screen reader should be announced that saved confirmation also saved message should appear on screen so that users easily know that the action was completed and transcript get saved.
**Repro …
=> [Accessibility] [Screen Reader] Show message after saving the transcripts in the Live Chat panel

packages/sdk/ui-react/src/layout/expandCollapse/expandCollapse.scss, packages/sdk/ui-react/src/layout/expandCollapse/expandCollapse.scss.d.ts, packages/sdk/ui-react/src/layout/expandCollapse/expandCollapse.tsx
If users Navigate on Side pane control and expand/collapse Chat file and Transcript, screen reader state information does not announce for that control, and it would be confusing for users to know the action was completed or not.
Screen reader Expand/Collapse state information does not announced for Chat file and Transcripts control under present Resources controls.
Screen reader Expand/Collapse state information should be announced for Chat file and Transcripts control under present Resources controls.
4. New BOT Configuration …
=> [Accessibility] [Screen Reader] Enable screen reader to announce when the panel is collapsed or expanded

packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.spec.tsx, packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.tsx, packages/app/client/src/ui/editor/emulator/parts/inspector/inspectorContainer.ts
If users navigate on JSON section under Chat with Bot screen, and select copy JSON and it get copied but visually message not appear on screen, then it would difficult for users to know JSON get copied or not, perform action get completed or not.
When users connect using the Bot screen and navigate to the JSON section and select Copy JSON control and it gets selected, but the copied message does not visually appear on screen, and it would be difficult for users to know the action is completed or not.
When users connect using the Bot screen and navigate to the JSON section and select Copy JSON control and it gets selected, a copied message should visually appear on the screen, so that users easily know JSON get copied.
1. Open …
=> [Accessibility] [Screen Reader] Show a message after copying the JSON from the inspector panel

packages/app/main/src/commands/emulatorCommands.spec.ts, packages/app/main/src/commands/emulatorCommands.ts
If users Navigate on the File menu item and select the Clear State option and a pop-up appears and focus land on the OK button but the keyboard focus indicator is not visible on the Ok button, then it would be difficult for users to understand where the focus indicator landed.
Navigating on the File menu item and select the Clear State option and a pop-up appears and the keyboard focus indicator lands on the OK button but visually keyboard focus indicator is not visible on the Ok button.
Navigating on the File menu item and select the Clear State option and a pop-up appears and the keyboard focus indicator lands on the OK button, So visually keyboard focus indicator should be visible on the Ok button.
1. Open Bot Framework …
=> [Accessibility] [Keyboard Navigation] Fix the focus indicator on the Clear State popup dialog

packages/app/client/src/ui/shell/explorer/servicePane/servicePane.tsx
If users Navigate on Side pane control and focus moves to the Add control under the Bot Explorer panel the screen reader announcement is not descriptive enough to identify the purpose of the control.
Screen reader descriptive information does not announce for Endpoint add control and Services add control, screen reader only add button announce and it confusing for users to know which control and what purpose of the control.
Screen reader descriptive information should be announced for Endpoint add control and Services add control so that users easily identify the purpose of the control and perform an action accordingly. E.g.: it should be announced as "Add endpoint button" and "Add services button".
1. Open Bot Framework …
=> [Accessibility] [Screen Reader] Fix the "Add" button announcement for the Bot Explorer panel

packages/app/client/src/ui/shell/appMenu/appMenuTemplate.ts, packages/app/client/src/utils/eventHandlers.ts
If users Navigate on toggle full-screen menu item and selection of that control also exit full screen, the screen reader announces same information for both times and it would be confusing for screen reader users if the action is completed or not.
Navigating on View menu item and select toggle full-screen and exit full screen with shortcut key which provided with control, screen reader provided same information after performing the action on both times.
Navigating on View menu item and select toggle full screen and exit full screen with shortcut key which provided with control, screen reader should be provided proper information at full screen, it should announce full screen at exit full screen. it should be announced as exit full screen. …
=> [Accessibility] [Screen Reader] Add a screen reader announcement when the toggle full-screen option is enable or disable

packages/app/client/src/ui/styles/themes/light.css
If users Navigate on the Bot explorer section and the luminosity ratio is less than for added endpoint http://local... text and it would be difficult for users to understand the text.
Luminosity ratio is less than for added endpoint http://local... text, under Bot Explorer.
Luminosity ratio should be equal or more than for added endpoint http://local... text, under Bot Explorer.
4. New BOT Configuration dialog opens.
5. Navigate on the dialog and enter inputs in edit fields then select the save and connect button.
6. Navigate to …
=> [Accessibility] [Keyboard Navigation] Fix luminosity ratio in Bot Explorer list items

packages/app/client/src/ui/shell/explorer/botExplorerBar/botExplorerBar.tsx, packages/app/client/src/ui/shell/explorer/botNotOpenExplorer/botNotOpenExplorer.tsx, packages/app/client/src/ui/shell/explorer/resourcesBar/resourcesBar.tsx, packages/app/client/src/ui/shell/explorer/servicePane/servicePane.tsx, packages/sdk/ui-react/src/layout/expandCollapse/expandCollapse.tsx
If users select Resources control and pane gets appear but keyboard focus indicator remain on the same control and does not land on first interactive control on Resources pane, then it would lengthy process to users to navigate on Resources pane. The user needs to navigate on all control to move on the Resources pane.
After selecting the Resource control pane gets appears but the keyboard focus indicator remains on the same control, it does not land on the first interactive control on the Resource pane.
After selecting the Resource control pane gets appears, the keyboard focus indicator should be land in the first interactive control on the Resource pane, it should not remain on the same control.
1. Open Bot Framework Emulator …
=> [Accessibility] [Keyboard Navigation] Enable left panels to focus on the first interactive element

packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.scss, packages/app/client/src/ui/editor/panel/panel.scss
If users Navigate on the JSON section and the hide diff button is available on this section and it's not accessible and visible using the keyboard navigation, then it would be difficult for users to know which control is available on there and the purpose of that control.
Navigating on the JSON section, the Hide diff button is available but that control is not accessible and visible using the keyboard navigation.
Navigating on the JSON section, the Hide diff button is available so that control should be accessible and permanently visible using the keyboard navigation.
3. Navigate on the welcome screen and …
=> [Accessibility] [Keyboard Navigation] Remove hidden buttons from the Inspection panel to avoid being accessible using the mouse

packages/app/main/src/main.ts
If color blind users navigate on Welcome screen and screen does not adopting high contrast, then it would be difficult for users to navigate on screen and complete their task.
After applying High contrast, Welcome screen does not adapt high contrast setting.
After applying High contrast, Welcome screen should adapt this setting.
3. Navigate on the welcome screen.
4. Verify that screen adopting High contrast setting or not.
- Added the `shouldUsehighContrastColors` property along with the `shouldUseInvertedColorScheme` one to validate if the high contrast theme should be applied
Windows (high contrast) 
macOS …
=> [Accessibility] [Supporting Platforms] Fix the Emulator's color theme when using the High Contrast property on Linux

packages/sdk/ui-react/src/widget/autoComplete/autoComplete.spec.tsx, packages/sdk/ui-react/src/widget/autoComplete/autoComplete.tsx
If screen reader users navigate on the Open a bot dialog box and enter an invalid keyword, an error message appears but the screen reader does not announce that information, so it would be difficult for users to understand what has done wrong.
After entering an invalid keyword in the Bot URL edit field, an error message appears "Please choose a valid bot file or endpoint URL", but the screen reader does not announce that appear message information.
After entering an invalid keyword in the Bot URL edit field, an error message appears "Please choose a valid bot file or endpoint URL", So the screen reader should be announcing this information.
2. Bot Framework Emulator …
=> [Accessibility] [Screen Reader] Fix the screen reader announcement when an invalid URL is entered

packages/app/client/src/ui/shell/navBar/navBar.scss, packages/app/client/src/ui/shell/navBar/navBar.tsx, packages/app/client/src/ui/styles/themes/dark.css, packages/app/client/src/ui/styles/themes/high-contrast.css, packages/app/client/src/ui/styles/themes/light.css
If users Navigate on Resources and Bot Explorer control and tooltip is not appearing for that control, then it would be difficult for users to understand control, if users don't know about the control icon, they would be unable to identify the control icons.
When users navigate on Resource and Bot Explorer control Present side pane and tooltip is not appearing for that control and it confusing for users which control is that.
When users navigate on Resource and Bot Explorer control Present side pane So tooltip should appear for that control.
3. Navigate on the welcome screen and select Create a New BOT …
=> [Accessibility] [Supporting Platforms] Add a tooltip for keyboard navigation to the left panel

packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx
If Keyboard users navigate on Chat with BOT screen and enter any message and it gets failed and retry and restart conversation control is appearing on chat section but, it does not accessible with keyboard navigation, then it would be difficult for users to complete their task.
When the user navigates on Chat with Bot screen and enters any message and send it and it gets failed and after that retry and restart conversation control is appearing but users would be unable to access that control with keyboard navigation under chat section.
When the user navigates on Chat with Bot screen and enters any message and send it and it gets failed and after that retry and restart conversation control is appearing, So users should be unable to access that …
=> [Accessibility] [Keyboard Navigation] Fix the focus on the Retry and Restart conversation buttons

packages/app/client/src/ui/shell/explorer/notificationsExplorer/notificationsExplorer.scss, packages/app/client/src/ui/shell/explorer/notificationsExplorer/notificationsExplorer.scss.d.ts, packages/app/client/src/ui/shell/explorer/notificationsExplorer/notificationsExplorer.tsx
If users select notification control and there is no notification available and the screen reader does not announce that information, so it would be difficult for users to know there is notification available or not.
After selecting the Notification control, the notification pane appears but the screen reader does not announce the "No New notification" message.
After selecting the Notification control, the notification pane appears so the screen reader should announce "No New notification".
4. New BOT Configuration dialog opens. …
=> [Accessibility] [Screen Reader] Add a screen reader announcement when expanding the Notifications panel

packages/app/client/src/ui/shell/mdi/tab/tab.scss, packages/app/client/src/ui/shell/mdi/tab/tab.scss.d.ts, packages/app/client/src/ui/shell/mdi/tab/tab.tsx
If screen reader users navigate on the welcome screen and the welcome tab is selected but the screen reader does not announce the selected state, so it would be difficult for users to understand which tab is selected.
When the user navigates on the tab section and the Welcome tab is selected, the screen reader is not announcing the selected state for Welcome Tab.
When the user navigates on the tab section and the Welcome tab is selected, the screen reader should announce the selected state for Welcome Tab.
3. Navigate to the welcome screen.
4. Verify whether the screen reader is announcing the selected state …
=> [Accessibility] [Screen Reader] Add a screen reader announcement for the active tab on Linux

packages/sdk/ui-react/src/widget/menu/menuItem.spec.tsx, packages/sdk/ui-react/src/widget/menu/menuItem.tsx
If users on the file menu and shortcut key available with controls and screen reader is not announcing that shortcut keys information, then it would be difficult for users to know there is a shortcut key available with control.
When the user expands the file menu and a shortcut key is available with controls, but the Screen reader is not announcing available Shortcut key information with control.
When the user expands the file menu and a shortcut key is available with controls, the Screen reader should be announcing available Shortcut key information with control. So that users use the shortcut key.
3. …
=> [Accessibility] [Screen Reader] Add a screen reader announcement for menu shortcuts

packages/sdk/ui-react/src/layout/expandCollapse/expandCollapse.tsx
If the screen reader is not providing the information, you do not have any chat files under chat files, then it would be difficult for users to know is there any chat file available or not.
When users navigate on the Resource section and expand Chat files, the Screen reader is not providing information "you do not have any chat files in dialog" under Chat files.
When users navigate on the Resource section and expand Chat files, So Screen reader should be announcing "you do not have any chat files in dialog" information, so that users know there is no chat file available.
3. Navigate on the welcome screen and …
=> [Accessibility] [Screen Reader] Fix the screen reader announcement when no chat/transcript files are available in the Resources panel

packages/app/client/src/ui/shell/explorer/botExplorerBar/botExplorerBar.tsx, packages/app/client/src/ui/shell/explorer/botNotOpenExplorer/botNotOpenExplorer.tsx, packages/app/client/src/ui/shell/explorer/resourcesBar/resourcesBar.tsx, packages/app/client/src/ui/shell/explorer/servicePane/servicePane.tsx, packages/sdk/ui-react/src/layout/expandCollapse/expandCollapse.tsx
If screen reader announcing role as a toolbar for chat file and transcripts control, rather than drop-down or button, so it would be difficult for users to understand the purpose of the control and would be get confused about the control role.
Screen reader announcing role as a toolbar for "Chat files and Transcripts" control under Resource section. And it's confusing for users to understand the control role.
Screen reader should not announce role as a toolbar for "Chat files and Transcripts" control, it should be announced role as a drop-down or button for "Chat files and Transcripts" control, rather than toolbar under Resource section.
2. Bot Framework Emulator …
=>  [Accessibility] [Visual Requirements] Fix the role announced by the screen reader when focusing the left panels

packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.tsx, packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.tsx, packages/sdk/ui-react/src/widget/textField/textField.tsx
If screen reader users navigate on the Open a bot dialog box and focus on the Microsoft app password field and screen reader announcing password word twice, then it would be confusing for users to understand how many password field is available there.
Screen reader announcing "Password" word twice with "Microsoft app password" field, under Open a bot dialog box.
Screen reader should not announce the "Password" word twice with the "Microsoft app password" field, under the Open a bot dialog box.
It should announce only one time.
3. Navigate on the welcome screen and select the Open Bot button.
4. Open A bot …
=> [Accessibility] [Screen Reader] Fix the screen reader announcement for the "Microsoft App password" field

packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.tsx
If screen reader users navigate on JSON section and screen reader button announcing with JSON, then it would be confusing for users because it is not functional, it's not working as like button.
When the focus moves on the JSON section, the Screen reader announces its role as a Button with JSON, but it is not functional, it is not working as a button.
When the focus moves on the JSON section, So Screen reader role as a Button should not announce with JSON, because it is not functional, and it is confusing for the users, after performing an action on control nothing happens.
3. Navigate on the welcome screen …
=> [Accessibility] [Screen Reader] Fix the JSON button role in the Inspection panel

packages/app/client/src/ui/dialogs/connectServicePromptDialog/connectServicePromptDialog.tsx
If users select Add Language Understanding (LUIS) and dialog get open but the screen reader does not announce open dialog information, then it would be difficult for users to understand after the dialog was opened or not.
After selection of Add Language Understanding (LUIS) control dialog gets open but open dialog information does not provide by the screen reader.
After selection of Add Language Understanding (LUIS) control dialog gets open but open dialog information does not provide by the screen reader.
4. New BOT …
=> [Accessibility] [Screen Reader] Fix the Connect Service dialog to be read by the screen reader

packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.spec.tsx, packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.tsx, packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialogContainer.ts, packages/app/client/src/ui/dialogs/botSettingsEditor/botSettingsEditor.spec.tsx, packages/app/client/src/ui/dialogs/botSettingsEditor/botSettingsEditor.tsx, packages/app/client/src/ui/dialogs/botSettingsEditor/botSettingsEditorContainer.ts
If users navigate on the New Bot Configuration Dialog and focus moving on copy control and select it, but the copy message does not appear on screen, so it would be difficult for users to understand if the action was completed or not.
After selection of the Copy control, a "Copied message" does not appear on the screen Under Bot Configuration Dialog.
After selection of the Copy control, a "Copied message" should appear on the screen Under Bot Configuration Dialog. So that users know that the action was completed.
4. New BOT …
=> [Accessibility] [Visual Requirement] Added a visual message when clicking the Copy button in bot dialogs

packages/app/client/src/ui/shell/appMenu/appMenuTemplate.ts, packages/app/client/src/utils/eventHandlers.ts
If users Navigate on toggle full screen menu item and select it of that control also exit full screen, the screen reader is not announcing the same information about for both time and it would be confusing for screen reader users perform action is correct or not.
Navigating on View menu item and select it to toggle full screen control and exit full screen also with shortcut key which provided with control, visually message is not appearing on screen also screen reader is not provided the same information after performing the action on both times.
Navigating on View menu item and select it to toggle full screen and exit full screen also with shortcut key which provided with control, visually message should appear also screen reader should be …
=> [Accessibility] [Screen Reader] Add a visual message when using the full screen option

packages/app/client/package.json, packages/app/client/src/ui/editor/editor.tsx, packages/app/client/src/ui/editor/markdownPage/markdownElement.spec.tsx, packages/app/client/src/ui/editor/markdownPage/markdownPage.tsx
If users navigate on getting started with channel screen and after open screen, focus indicator does not land on first interactive control, so it would be difficult for users to understand focus order on the screen.
After selection of Get Started with Channel (Bot Inspector) control screen gets open but the focus indicator does not land on the first interactive control.
After selection of Get Started with Channel (Bot Inspector) control screen get open, So the focus indicator should be not land on the first interactive control. So that users easily navigate on the screen.
3. Navigate on the welcome screen and …
=>  [Accessibility] [Screen Reader] Fix the focus on the Get Started with Channel page

scripts/rebasePackageLock.js
This PR takes a script from the Web Chat repo, that takes a `package-lock.json` file as an input and outputs a modified `package-lock.json` with all the package source URLs pointing to a specified feed URL.
This allows us to fetch all of our upstream NPM dependencies from a custom source, in this case, an internal Azure Artifacts feed.
**Proof of all Emulator builds successfully building off of this branch: (still waiting for nightly build)**
=> Added script to redirect upstream npm dependency source

credScanTargetFoldersWindows.tsv
This is a follow-up PR to #2371.
The paths in that PR are not Windows-friendly and so a separate file needs to be added.
=> Added CredScan paths for Windows agents

packages/app/client/src/commands/uiCommands.ts, packages/app/client/src/ui/dialogs/service/dialogService.spec.tsx, packages/app/client/src/ui/dialogs/service/dialogService.ts
Normally, there is no way for a user to open a dialog when another dialog has been opened. However, this occurs when the "Updates available" dialog is opened as a result of the 'update-available' event.
Added a method to wait for the currently displayed dialog to be hidden, and used it for the "Updates available" dialog.
Fixes [VSTS-63986](https://fuselabs.visualstudio.com/Composer/_workitems/edit/63986)
=> fix: keyboard shortcuts don't work when telemetry and updates dialogs appear together

packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx, packages/app/client/src/ui/shell/explorer/botExplorerBar/botExplorerBar.tsx, packages/app/client/src/ui/shell/mdi/tab/tab.scss, packages/app/client/src/ui/shell/mdi/tab/tab.scss.d.ts, packages/app/client/src/ui/shell/mdi/tab/tab.tsx, packages/sdk/ui-react/src/layout/expandCollapse/expandCollapse.tsx, packages/sdk/ui-react/src/utils/menu.ts, packages/sdk/ui-react/src/utils/os.ts, packages/sdk/ui-react/src/widget/menu/menuItem.spec.tsx, packages/sdk/ui-react/src/widget/menu/menuItem.tsx, packages/sdk/ui-react/src/widget/menu/subMenu.tsx, packages/sdk/ui-react/webpack.config.js
1. [VSTS-63988](https://fuselabs.visualstudio.com/Composer/_workitems/edit/63988) The [default `"complementary"`](https://github.dev/microsoft/BotFramework-WebChat/blob/6a5359f4b74827f9b8919eaf802aa0374217ed15/packages/component/src/BasicWebChat.tsx#L76) role cannot be included into another landmark. Use `"region"` role for the chat instead.
2. [VSTS-64729](https://fuselabs.visualstudio.com/Composer/_workitems/edit/64729) On linux, when using orca, it doesn't announce an actual role for menu items. Fixed by adding the "menu item" text `aria-description` property only on linux
3. [VSTS-64703](https://fuselabs.visualstudio.com/Composer/_workitems/edit/64703) Sidebar section header buttons had a `toolbar` role which is not descriptive. Fixed by changing the role to `button` and adding …
=> a11y: fix platform-specific issues

packages/app/client/src/commands/uiCommands.spec.ts, packages/app/client/src/commands/uiCommands.ts, packages/app/client/src/state/sagas/presentationSagas.ts, packages/app/client/src/ui/shell/appMenu/appMenu.tsx, packages/app/client/src/ui/shell/appMenu/appMenuTemplate.ts, packages/app/client/src/utils/eventHandlers.spec.ts, packages/app/client/src/utils/eventHandlers.ts, packages/app/main/src/appMenuBuilder.ts, packages/app/main/src/commands/clientInitCommands.spec.ts, packages/app/main/src/commands/clientInitCommands.ts, packages/app/main/src/commands/electronCommands.spec.ts, packages/app/main/src/commands/electronCommands.ts, packages/app/main/src/main.spec.ts, packages/app/main/src/main.ts, packages/app/shared/src/constants/sharedConstants.ts
* Add announcement for theme switching for macOS
* Make the theme switching message to start with visible content
* Move the full screen command to the UI commands and add announcement
* Refactor code to use full screen command instead of calling BrowserWindow API directly
* Update tests
[VSTS-64005](https://fuselabs.visualstudio.com/Composer/_workitems/edit/64005)
=> a11y: announce theme switching and fullscreen commands

package-lock.json, packages/app/main/package.json, packages/app/main/src/fetchProxy.spec.ts, packages/app/main/src/fetchProxy.ts, packages/app/main/src/server/routes/directLine/handlers/upload.ts
This addresses the following issues:
- Insecure TLS connections allowed: 
- removed the code and added a way to specify a certificate for self-signed / local setup
- updated `https-agent-proxy` package to enable additional options support
- Insecure `fs` module usage:
- added code to check against root. As we rely on temporary files location for form submitted files and on user-specified certificates, the folder can be located anywhere. Using `''` as the root allows to resolve both relative and absolute paths properly.
Note that the change restricts using non-trusted by NodeJS built-in certificates for HTTPS connections, unless the certificate is provided either via `NODE_EXTRA_CA_CERTS` or `HTTPS_PROXY_CA`. Alternatively users can disable the check globally by specifying …
=> Security: address TLS/FS issues

.github/ci.yaml, .github/pack.yaml
Adds two pipelines to GitHub. These are not replacing ADO pipelines, are used to get a faster indicator using GitHub Actions
=> Add GH Actions for CI and pack
