microsoft/BotFramework-Emulator

- ThirdPartyLicenses.txt
- package.json
- src/server/botFrameworkService.ts
- src/server/conversationManager.ts
- src/types/activityTypes.ts
localTimestamp is new property 
ngrok rate limits and so no need to use for local to local activity
> Add localTimestamp and bypass ngrok with localhost urls 

- src/server/main.ts
makes it easy to select the entire message to copy or delete
> Added select all to menubar/titlebar

- package.json
- src/client/mainView.tsx
Also:
- Handle resizing of chat control.
- Pull in `wc-app` CSS class from botchat. Chat component needs it.
> update to latest webchat control

- src/client/addressBar/addressBarMenu.tsx
- src/client/emulator.ts
- src/server/controllers/emulator/emulatorController.ts
- src/server/main.ts
Zoom functions are now available in the address bar menu.
> Added zoom to address bar menu

- src/client/dialogs/appSettingsDialog.tsx
- src/utils.ts
Fixed some more issues raised in the original pull request. Fixed two bugs in the approximateObjectSize function and slightly changed label for the state size input.
> approximateObjectSize bug fix and change to size limit label.

- src/shared/utils.ts
Adding unit tests revealed a flaw in utils.isSecureUrl, which this fixes. Also added some types to the other util functions, just for good measure.
> Fix broken unit test in isSecureUrl, and add types to util.ts functions.

- src/server/main.ts
- src/server/windowManager.ts
With the recent PR that added more short cuts, we added electron-shortcuts. Change over the older shortcuts to use this new and superior system.
> Change zoom shortcuts to use electron-localshortcut

- src/client/css/emulator.css
- src/client/dialogs/aboutDialog.tsx
- src/client/dialogs/appSettingsDialog.tsx
- src/client/dialogs/commonDialog.tsx
- src/client/dialogs/conversationSettingsDialog.tsx
- add dialog component for use in appSettings, aboutDialog, & conversationsSettingsDialog
- add focus trap on dialog
- some styling fixes so that focus is visible on elements within dialog
- changed standard blue to constrast compliant one
> Focus trap & dialog component

- package.json
- tests/integration/integration.ts
- tests/testBot/testBot.ts
Added a way to bring up the payment window with the testbot, and added integration tests to test this functionality. Also update the BotBuilder package.
> Added test for payment window to integration test.

- .vscode/launch.json
- package.json
- src/server/restServer.ts
Also support attach to existing emulator process
> Add CORS for localhost debugging

- src/server/controllers/directLine/conversationsControllerV3.ts
Fixes https://github.com/Microsoft/BotFramework-Emulator/issues/407
> Replace Number.MAX_VALUE with (2^31)-1

- package.json
- src/server/OpenIdMetadata.ts
- src/server/botFrameworkService.ts
- src/server/conversationManager.ts
- src/server/emulator.ts
- src/server/ngrok.ts
- src/server/versionManager.ts
Related to #363 . Most recent version of got does not work with electron.net due to an Electron bug.
> Change server side requests to 'got', to take advantage of electron.net

- packages/app/main/gulpfile.js
- packages/extensions/qnamaker/client/package-lock.json
- packages/extensions/qnamaker/client/package.json
- packages/extensions/qnamaker/client/src/App.tsx
- packages/extensions/qnamaker/client/src/AppStateAdapter.tsx
- packages/extensions/qnamaker/client/src/Models/QnAMakerModels.ts
- packages/extensions/qnamaker/client/src/QnAMaker/Client.ts
- packages/extensions/qnamaker/client/src/Views/AnswersView.tsx
Update to QnAMaker extension to make it work the QnAMaker v4 api. The bot build tools have another fix that will need to be completed and deployed before this will work totally, but after that the extension should be good to go. 
Also included is a fix so the extension builds with everything else.
> Update QnAMaker extension to work with v4 QnAMaker api.

- packages/app/main/src/appMenuBuilder.ts
Point to the proper link for the license.
> update license link

- src/server/conversationManager.ts
Casing of OAuthClientEncoder import was wrong
> Casing of OAuthClientEncoder import was wrong

- packages/extensions/qnamaker/client/src/App.tsx
- packages/extensions/qnamaker/client/src/QnAMaker/Client.ts
QnAMaker's update knowledge base returns a operation id which is used to poll for a completed training operation.
> Polling training

- packages/app/client/src/ui/dialogs/botCreationDialog.tsx
- packages/sdk/ui-react/src/styles/colors.ts
- packages/sdk/ui-react/src/widget/textInputField.tsx
- Added correct focus / error / disabled border colors
- Adjusted spacing
- Adjusted font sizes
- Adjusted font colors
> Changed text input field component to match design specs.

- packages/app/main/package.json
- packages/emulator/core/package.json
- packages/extensions/debug/client/package.json
- packages/sdk/ui-react/package.json
Literally,
```
lerna add tslint --dev --hoist --scope=@bfemulator/main --scope=@bfemulator/emulator-core
lerna add webpack --dev --hoist --scope=@bfemulator/ui-react --scope=@bfemulator/extension-debug-client
```
> Fix missing dev deps

- packages/extensions/qnamaker/bf-extension.json
- packages/extensions/qnamaker/client/.gitignore
- packages/extensions/qnamaker/client/package.json
- packages/extensions/qnamaker/client/public/index.html
- packages/extensions/qnamaker/client/src/App.tsx
- packages/extensions/qnamaker/client/src/Views/PhrasingsView.tsx
- packages/extensions/qnamaker/client/webpack.config.js
Fixes for the QnA Maker extension which let it build again, and also some clean up, like improved formatting and selecting answers when they're added.
> Qnamaker build clean

- packages/emulator/core/src/directLine/middleware/postActivity.ts
> Show a meaningful message when the bot returns HTTP 401/403

- packages/app/client/src/data/sagas/editorSagas.ts
- packages/app/client/src/hyperlinkHandler.ts
- packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.tsx
- packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditor.tsx
- packages/app/client/src/ui/editor/emulator/parts/log/log.tsx
- packages/app/client/src/ui/shell/explorer/fileExplorer/fileExplorer.tsx
- packages/app/client/src/ui/shell/navBar/navBarContainer.ts
- packages/app/main/src/commands/clientInitCommands.ts
- packages/app/main/src/commands/oauthCommands.ts
- packages/app/main/src/protocolHandler.ts
- packages/app/shared/src/constants/sharedConstants.ts
As mentioned in the Theming PR #665
> Fixed some left-over legacy / mismatched commands.

- packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx
- packages/emulator/core/src/facility/botEndpoint.ts
> Fix speech token exchange

- packages/app/client/src/data/sagas/dispatchSagas.ts
- packages/app/client/src/data/sagas/luisSagas.ts
- packages/app/client/src/data/sagas/qnaMakerSagas.ts
Related to #711 
==========
Changed text for services context menu.
> Changed text for service context menu 'remove' item

- packages/app/client/src/commands/emulatorCommands.ts
- packages/app/client/src/commands/notificationCommands.ts
- packages/app/client/src/index.tsx
- packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.tsx
- packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditor.tsx
- packages/app/client/src/ui/editor/emulator/emulator.tsx
- packages/app/client/src/ui/helpers/activeBotHelper.ts
- packages/app/main/src/protocolHandler.ts
Fix for #490 
========
Some application functionality was silently failing instead of letting the user know what failed and why. Added some error handling that will create a notification with information about the error.
> Certain application errors will now notify the user with a notification.

- package-lock.json
- packages/app/client/package.json
- packages/extensions/debug/main/package.json
- packages/extensions/luis/client/package.json
- packages/extensions/qnamaker/client/package.json
- packages/sdk/ui-react/package.json
Make sure `@types/react` is using similar version to `react@~16.3.2`.
It seems `typescript@2.7.2` and `@types/react@16.4.9` are not liking each other.
> Use @types/react@~16.3.2

- packages/app/client/src/ui/editor/welcomePage/welcomePage.scss
- packages/app/client/src/ui/editor/welcomePage/welcomePage.scss.d.ts
- packages/app/client/src/ui/editor/welcomePage/welcomePage.tsx
- packages/app/client/src/ui/editor/welcomePage/welcomePageContainer.ts
- packages/app/client/src/ui/styles/themes/dark.css
- packages/app/client/src/ui/styles/themes/high-contrast.css
- packages/app/client/src/ui/styles/themes/light.css
Fix for #619 
==========
- Styled according to final design spec
- Added theming
> Final design for bot list delete ui.

- packages/app/main/src/commands/botCommands.ts
Related to #619 
===========
Added a native confirmation dialog before carrying out deletion
> Added a native confirmation dialog before deleting a bot from My Bots

- packages/app/client/src/ui/styles/themes/dark.css
- packages/app/client/src/ui/styles/themes/high-contrast.css
- packages/app/client/src/ui/styles/themes/light.css
Resolves issue [#758: [MAS1.4.3] Luminosity Contrast Ratio of links present on Welcome screen (in blue) is less than required 4.5:1.](https://github.com/Microsoft/BotFramework-Emulator/issues/758) 
Dark & High Contrast Themes: #3794FF
Light Theme: #006AB1
> Update links to meet contrast ratio requirements

- packages/app/client/src/data/sagas/servicesExplorerSagas.spec.ts
- packages/app/client/src/data/sagas/servicesExplorerSagas.ts
- packages/app/main/package.json
- packages/app/main/src/commands/botCommands.spec.ts
- packages/app/main/src/commands/botCommands.ts
- packages/app/main/src/services/luisApiService.ts
- packages/app/shared/src/types/luisTypes.ts
> Added luis link support by region

- packages/app/client/src/ui/shell/mdi/tab/tab.scss
- packages/app/client/src/ui/shell/multiTabs/multiTabs.scss
- packages/app/client/src/ui/styles/themes/dark.css
- packages/app/client/src/ui/styles/themes/high-contrast.css
- packages/app/client/src/ui/styles/themes/light.css
> Fix border on keyboard focus of navbar

- packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditor.scss
- packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditor.scss.d.ts
- packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditor.tsx
- packages/app/client/src/ui/styles/themes/high-contrast.css
- packages/app/client/src/ui/styles/themes/light.css
Resolves #739 
- some css cleanup
- anchors on emulator settings page are now accessible
> Corinagum 739 emulator settings links

- packages/app/main/package.json
Fix for #865 
========
Build step was no longer copying extensions into the built directory for some reason.
> Added gulp command to build script to copy extensions to built dir.

- packages/app/client/src/ui/editor/emulator/parts/detail/detail.scss
- packages/app/client/src/ui/editor/emulator/parts/detail/detail.tsx
- packages/app/client/src/ui/editor/emulator/parts/log/log.scss
- packages/app/client/src/ui/editor/emulator/parts/log/log.scss.d.ts
- packages/app/client/src/ui/editor/emulator/parts/log/logEntry.tsx
Resolves #747 
Resolves #742 
Log details interact-ables are not accessible via keyboard
Inspector panel now focus-able
> Update Inspector & Log sections to be accessible via keyboard

- packages/app/client/src/ui/editor/emulator/chatPanel/chatPanel.scss
- packages/app/client/src/ui/editor/emulator/logPanel/logPanel.scss
- packages/app/client/src/ui/editor/toolbar/toolbar.scss
- packages/app/client/src/ui/shell/explorer/servicesExplorer/servicesExplorer.scss
- packages/app/client/src/ui/shell/explorer/servicesExplorer/servicesExplorer.scss.d.ts
- packages/app/client/src/ui/shell/explorer/servicesExplorer/servicesExplorer.tsx
- packages/app/client/src/ui/shell/explorer/servicesExplorer/servicesExplorerContainer.ts
- packages/app/client/src/ui/styles/themes/dark.css
- packages/app/client/src/ui/styles/themes/high-contrast.css
- packages/app/client/src/ui/styles/themes/light.css
> Explorer pane empty content update & splitter border

- packages/app/client/src/ui/dialogs/secretPromptDialog/secretPromptDialog.tsx
> Fixed disabled submit button issue in secret prompt dialog.

- packages/app/client/src/ui/shell/statusBar/statusBar.scss
- packages/app/client/src/ui/shell/statusBar/statusBar.tsx
- packages/app/client/src/ui/styles/themes/dark.css
- packages/app/client/src/ui/styles/themes/high-contrast.css
- packages/app/client/src/ui/styles/themes/light.css
> Corrected status bar color and content.

- packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditor.scss
- packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditor.scss.d.ts
- packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditor.tsx
Fixes #869 
=====
No spec was available so might need minor polish later.
> Improved spacing / sizing in app settings page.

- packages/app/main/src/services/azureAuthWorkflowService.ts
> #976 - azure sign in tool now prompts for username with each login

- packages/app/client/src/ui/shell/explorer/servicePane/servicePane.scss
> #945 - Verly long service lists are now scrollable

- package-lock.json
- packages/app/main/gulpfile.mac.js
- packages/app/main/gulpfile.windows.js
- packages/app/main/package-lock.json
- packages/app/main/package.json
- packages/app/main/scripts/config/windows-nsis.json
- packages/app/main/src/appMenuBuilder.ts
- packages/app/main/src/appUpdater.ts
- packages/app/main/src/main.ts
Fix for #546 
====
- Fixed signing for Mac.
- Minor changes to auto update UI & flow
- Removed redundant / unused code in mac and windows build processes
- Fixed some issues with nightly versioning
> Fixed signing & auto update on Mac build.

- packages/app/client/src/commands/botCommands.spec.ts
- packages/app/client/src/commands/botCommands.ts
- packages/app/client/src/data/action/resourcesAction.ts
- packages/app/client/src/data/reducer/resourcesReducer.ts
- packages/app/client/src/ui/shell/explorer/resourceExplorer/resourceExplorer.spec.tsx
- packages/app/client/src/ui/shell/explorer/resourceExplorer/resourceExplorer.tsx
- packages/app/client/src/ui/shell/explorer/resourceExplorer/resourceExplorerContainer.ts
- packages/app/client/src/ui/shell/explorer/resourcesBar/resourcesBar.spec.tsx
- packages/app/client/src/ui/shell/explorer/resourcesBar/resourcesBar.tsx
- packages/app/client/src/ui/shell/explorer/resourcesBar/resourcesBarContainer.ts
- packages/app/client/src/ui/shell/explorer/servicePane/servicePane.tsx
- packages/app/client/src/ui/shell/explorer/servicesExplorer/servicesExplorer.tsx
- packages/app/client/src/ui/styles/globals.scss
- packages/app/main/src/commands/botCommands.ts
- packages/app/shared/src/constants/sharedConstants.ts
> #944 - Updated the resources section based on comps

- CONTRIBUTING.md
Installed version has to match version specified in lerna.json
> update lerna version

- package-lock.json
- packages/app/client/src/extensions.ts
- packages/app/client/src/hyperlinkHandler.ts
- packages/app/client/src/platform/settings/settingsService.ts
- packages/app/main/src/watchers/botProjectFileWatcher.ts
- packages/extensions/luis/client/src/Adapters/RecognizerResultAdapter.tsx
- packages/extensions/luis/client/src/Luis/Client.ts
> #750 - Added guards agains 'startsWith' running on null

- CONTRIBUTING.md
> Added note about occasionally problematic missing Linux package.

- packages/app/main/scripts/config/windows-nsis.json
> Removed PREVIEW from windows shortcut name.

- packages/app/main/src/appMenuBuilder.ts
> Added 'Dismiss' button to About dialog.

- package-lock.json
- packages/app/client/src/commands/uiCommands.spec.ts
- packages/app/client/src/commands/uiCommands.ts
- packages/app/main/src/appMenuBuilder.ts
- packages/app/shared/src/constants/sharedConstants.ts
Resolves #820 
- Removed declaration of ShowExplorer  (ShowAppSettings is used by the LogEntry Component)
- ditched the generated qna change
> View menu text scrub (resolves #820)

- src/client/css/emulator.css
> Fixed missing borders on endpoint credential fields.

- packages/app/client/src/ui/shell/explorer/resourceExplorer/resourceExplorer.tsx
- packages/app/client/src/ui/shell/navBar/navBar.scss
- packages/app/client/src/ui/shell/navBar/navBar.tsx
- packages/app/client/src/ui/shell/navBar/navBarContainer.ts
> fixes #1048

- packages/app/client/src/data/sagas/endpointSagas.spec.ts
- packages/app/client/src/data/sagas/endpointSagas.ts
- packages/app/client/src/ui/dialogs/service/dialogService.ts
- packages/app/main/src/botHelpers.spec.ts
- packages/app/main/src/botHelpers.ts
- packages/app/main/src/commands/botCommands.spec.ts
- packages/app/main/src/commands/botCommands.ts
> #941 - added ABS deep linking in the endpoints expolorer

- src/server/main.ts
> Making sure 3.5.37 only updates to 4.

- package-lock.json
- packages/app/client/src/ui/editor/emulator/parts/chat/chat.scss
- packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.scss
- packages/app/client/src/ui/editor/welcomePage/welcomePage.scss
- packages/app/client/src/ui/shell/explorer/endpointExplorer/endpointExplorer.tsx
- packages/app/client/src/ui/shell/explorer/resourceExplorer/resourceExplorer.tsx
- packages/app/client/src/ui/shell/explorer/servicePane/servicePane.scss
- packages/app/client/src/ui/shell/explorer/servicesExplorer/servicesExplorer.tsx
- packages/app/client/src/ui/styles/globals.scss
- Minor syntax / cleanup
- Long entries in the explorer pane show text overflow ellipsis as per design spec
[no work item]
> Text overflow shows ellipsis in explorer panes

- package-lock.json
- packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/connectedServiceEditor.tsx
fixes #1100 
Added the subsctiptopn key to the list of editable fields for qnaMaker.
> Resolves #1100 - added the subscription key field to qna maker editor

- package-lock.json
- packages/app/client/src/constants.ts
- packages/app/client/src/data/sagas/botSagas.spec.ts
- packages/app/client/src/data/sagas/botSagas.ts
- packages/app/client/src/data/sagas/editorSagas.spec.ts
- packages/app/client/src/data/sagas/editorSagas.ts
- packages/app/main/src/appMenuBuilder.ts
- packages/app/main/src/commands/electronCommands.spec.ts
- packages/app/main/src/commands/electronCommands.ts
- packages/app/main/src/main.ts
- packages/app/shared/src/constants/sharedConstants.ts
> Refresh conversation menu when bot opens/closes

- packages/app/main/src/services/azureAuthWorkflowService.ts
This reverts commit 24ffcd5ba24e09e42802d73145f5aa854aabd39e, reversing
changes made to 3a858defe3fe3415b232613dd80db93b23f60a20.
> Revert "Merge pull request #1113 from Microsoft/ccastro/authv2"

- packages/app/client/src/data/sagas/servicesExplorerSagas.ts
- packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.scss.d.ts
- packages/app/client/src/ui/dialogs/connectServicePromptDialog/connectServicePromptDialog.tsx
- packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/connectedServiceEditor.spec.tsx
- packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/connectedServiceEditor.tsx
- packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServiceEditor/connectedServiceEditorContainer.ts
- packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServicePicker/connectedServicePicker.spec.tsx
- packages/app/client/src/ui/shell/explorer/servicesExplorer/connectedServicePicker/connectedServicePicker.tsx
- packages/app/client/src/ui/shell/explorer/servicesExplorer/servicesExplorerContainer.ts
- packages/app/client/src/utils/serviceTypeLables.ts
> Resolves #934 - add support for blob and cosmos db

- packages/app/main/package-lock.json
- packages/app/main/package.json
> Added missing dependency for proxy support

- packages/app/client/package-lock.json
- packages/app/client/package.json
This should resolve the issue that Tom was facing yesterday when building from a completely fresh enlistment.
> Added missing eslint-pugin-react dependency to client.

- CHANGELOG.md
- packages/app/client/src/ui/shell/explorer/explorerStyles.scss
- packages/app/client/src/ui/shell/explorer/resourcesBar/resourcesBar.scss
- packages/app/client/src/ui/shell/explorer/servicePane/servicePane.scss
- packages/app/client/src/ui/styles/themes/dark.css
- packages/app/client/src/ui/styles/themes/high-contrast.css
- packages/app/client/src/ui/styles/themes/light.css
> Fixed various resource pane styling issues.

- CHANGELOG.md
- packages/app/client/src/data/sagas/resourceSagas.spec.ts
- packages/app/client/src/data/sagas/resourcesSagas.ts
> Fixed transcript tab being overwritten on consecutive open.

- CHANGELOG.md
- packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.tsx
- packages/app/client/src/ui/shell/explorer/endpointExplorer/endpointEditor/endpointEditor.tsx
Fix for #1281 
===
**NOTE**: Still waiting on docs link & need to add entry in changelog
> Hooked up gov checkbox in new bot dialog.

- packages/app/client/src/hyperlinkHandler.ts
@justinwilaby you merged my other PR before I got the change in 😭
> Removed redundant remove().

- CHANGELOG.md
- packages/app/client/src/ui/editor/emulator/emulator.tsx
Cherry picking from `v4.3` branch into `master`
Original PR: #1325
> Fixed issue where restart conversation was not clearing history.

- CHANGELOG.md
- packages/app/client/src/ui/dialogs/openBotDialog/openBotDialog.tsx
> Altered open bot dialog copy.

- CHANGELOG.md
- packages/app/client/src/ui/editor/emulator/emulator.spec.tsx
- packages/extensions/luis/client/src/Adapters/AppStateAdapter.tsx
- packages/extensions/luis/client/src/App.tsx
- packages/extensions/qnamaker/client/src/AppStateAdapter.tsx
- packages/sdk/shared/src/types/activity/trace.ts
Cherry pick of #1334 into master.
> Fixed broken luis inspector.

- packages/app/client/src/ui/editor/emulator/parts/chat/chat.scss
> Allows text in chat window to be copied

- packages/app/main/src/services/luisApiService.spec.ts
- packages/app/main/src/services/luisApiService.ts
> Fixes #1356 - Cannot retrieve luis apps from regions other than westus

- CHANGELOG.md
- packages/app/client/src/ui/editor/emulator/parts/chat/chat.spec.tsx
- packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx
fixes #1358 
- [client] Do not render certain activities in webchat in PR [#1363](https://github.com/Microsoft/BotFramework-Emulator/pull/1363)
> do not render certain activity types in webchat

- CHANGELOG.md
- packages/extensions/luis/package-lock.json
- packages/extensions/qnamaker/package-lock.json
This commit should fix the GitHub security vulnerability alerts regarding dependencies within `extensions/luis` & `extensions/qnamaker`.
> Regenerated package-locks to fix security vulnerability.

- package-lock.json
- packages/app/client/package.json
- packages/extensions/luis/client/package.json
- packages/extensions/qnamaker/client/package.json
Don't think this deserves a changelog entry.
> Locked webpack-dev-server to 3.2.1 to fix local build.

- packages/app/client/src/ui/shell/explorer/botNotOpenExplorer/botNotOpenExplorer.scss
> Fixed theming on services explorer when bot isn't open.

- packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditor.tsx
- packages/app/client/src/ui/editor/emulator/emulator.scss
- packages/app/client/src/ui/editor/emulator/emulator.spec.tsx
- packages/app/client/src/ui/editor/emulator/emulator.tsx
- packages/app/client/src/ui/editor/emulator/toolbar/toolbar.scss
- packages/app/main/src/commands/settingsCommands.spec.ts
- packages/app/shared/src/types/serverSettingsTypes.ts
This reverts commit 2c6a4cf6d23fbd68d5029e28cd9010515bb6ec90.
> Revert "Allow the Emulator user to specify a User ID  (#1422)"

- CHANGELOG.md
- packages/app/client/src/commands/emulatorCommands.ts
> Fixed error thrown when cancelling opening a transcript.

- CHANGELOG.md
- packages/app/client/src/ui/editor/emulator/parts/log/log.scss
- packages/app/client/src/ui/styles/themes/dark.css
- packages/app/client/src/ui/styles/themes/high-contrast.css
- packages/app/client/src/ui/styles/themes/light.css
> Fixed invisible scrollbar styling in log panel.

- package-lock.json
- packages/app/client/src/ui/editor/emulator/parts/inspector/inspector.scss
- packages/app/client/src/ui/editor/panel/panel.scss
- packages/app/client/src/ui/styles/themes/dark.css
- packages/app/client/src/ui/styles/themes/high-contrast.css
- packages/app/client/src/ui/styles/themes/light.css
-- Styles to prevent the inspector accessory buttons from washing out in light theme mode. 
-- Addressed the focus rect being cut off
> Applied treatments for the accessory buttons in the inspector panel

- packages/app/client/src/ui/editor/emulator/parts/chat/chat.scss
> Updated the bot state button to use themed colors

- packages/app/client/src/data/sagas/chatSagas.ts
This PR provides proper selection of the previous bot state when diffing.
> Corrected diff selection process

- packages/sdk/shared/src/emulatorApi/conversationService.ts
> trimming input when starting conversations via url

- packages/app/main/src/services/azureAuthWorkflowService.ts
> Fixed #1455

- packages/app/client/src/data/sagas/chatSagas.ts
- packages/app/client/src/ui/editor/emulator/parts/chat/chat.scss
- packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx
- packages/app/client/src/ui/styles/themes/dark.css
- packages/app/client/src/ui/styles/themes/high-contrast.css
- packages/app/client/src/ui/styles/themes/light.css
> Updated bot state element according to new design

- packages/app/client/src/ui/editor/emulator/emulator.tsx
> Fixes #1475

- content/CHANNELS.md
- package-lock.json
- packages/app/main/src/appMenuBuilder.spec.ts
- packages/app/main/src/appMenuBuilder.ts
- packages/app/shared/src/constants/sharedConstants.ts
See https://github.com/Microsoft/BotFramework-Emulator/blob/cwhitten/bot-inspector/content/CHANNELS.md
> CHANNELS.md updates (and naming)

- packages/app/main/src/appMenuBuilder.spec.ts
- packages/app/main/src/appMenuBuilder.ts
> Added dev tools menu item.

- packages/app/main/src/commands/electronCommands.ts
> Fixed older node-fetch dep by the fbjs dependnecy used by React

- package-lock.json
- packages/app/client/src/data/sagas/chatSagas.ts
> Fixed an NPE when copying text from a bot state message

- packages/app/main/src/commands/botCommands.ts
> Fixed an issue with debug mode switching

- package.json
This new script `test:gen-lcov` is to be used by the automated CI build.
> Added script & config for generating test coverage.

- packages/app/client/src/data/sagas/chatSagas.ts
- packages/app/client/src/ui/editor/emulator/emulator.tsx
Fixes #1524 
ending direct line should occur only when the conversation is closed.
> fixed #1524

- README.md
…to reflect [V4 - Nightly] Master Build instead of Azure DevOps CI
> Build badge switched 

- CHANGELOG.md
- packages/extensions/luis/client/src/App.tsx
> Fixed the spinner issue when publishing LUIS after training

- packages/app/main/src/ngrokService.ts
> Fixes #1597

- packages/app/main/src/commands/emulatorCommands.spec.ts
- packages/app/main/src/commands/emulatorCommands.ts
Also added an `npm run lint` task to the CI build.
> Fixed some linting errors.

- package-lock.json
Had to run `lerna bootstrap --hoist` on a Linux VM to get the semver to bump the package properly. 🙄 
This is also related to #1578
> Regenerated lock file to bump axios to 18.0.1.

- CHANGELOG.md
There were some missing changelog entries that we forgot to add.
> Updated changelog with recent changes.

- package-lock.json
- packages/app/client/src/ui/editor/emulator/parts/log/log.tsx
- packages/app/client/src/ui/shell/mdi/documents/documents.spec.tsx
- packages/extensions/qnamaker/client/package-lock.json
- packages/extensions/qnamaker/client/package.json
- packages/extensions/qnamaker/client/public/index.html
- packages/extensions/qnamaker/client/webpack.config.js
- packages/sdk/ui-react/src/widget/splitButton/splitButtonPanel/splitButtonPanel.spec.tsx
Resolves #1635 
===
Updated the `qnamaker` dependency and the extension.
> Bumped the qnamaker dependency to 1.3.0

- CHANGELOG.md
- packages/app/client/src/data/sagas/chatSagas.ts
- packages/app/client/src/ui/editor/emulator/parts/chat/chatContainer.ts
> Fixed an issue where webSpeechFactories in store were being set to null.

- CHANGELOG.md
- packages/app/client/src/ui/editor/appSettingsEditor/appSettingsEditor.tsx
- packages/sdk/ui-react/src/widget/textField/textField.spec.tsx
- packages/sdk/ui-react/src/widget/textField/textField.tsx
#1762
===
Opening up the app settings page will now set focus to the ngrok path input field.
> [#1762] Fixed ngrok path focus issue in app settings editor.

- CHANGELOG.md
- packages/app/main/package.json
Merging `v4.6` branch into `master`
> v4.6.0 release.

- CHANGELOG.md
- packages/app/client/src/ui/editor/emulator/parts/chat/webChatTheme.ts
Revert the bubble background to use default color from webchat
> Removed bubble user background color. Leave it to default option

- CHANGELOG.md
- packages/app/client/src/ui/editor/emulator/parts/chat/webChatTheme.ts
- packages/app/client/src/ui/styles/themes/dark.css
- packages/app/client/src/ui/styles/themes/high-contrast.css
- packages/app/client/src/ui/styles/themes/light.css
> Fixed Web Chat suggestedActionBorder deprecation warning.

- CHANGELOG.md
- packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.spec.tsx
- packages/app/client/src/ui/dialogs/botCreationDialog/botCreationDialog.tsx
- packages/app/client/src/ui/editor/emulator/parts/chat/activityWrapper.tsx
- packages/app/client/src/ui/editor/emulator/parts/chat/chat.tsx
- packages/app/client/src/ui/editor/emulator/parts/chat/outerActivityWrapper.tsx
- packages/app/client/src/utils/copyToClipBord.spec.ts
- packages/app/client/src/utils/copyToClipboard.ts
Copy to clipboard fixed
Making sure restart conversation does not show up in Transcript or Debug mode
Signed-off-by: Srinaath Ravichandran <srravich@microsoft.com>
> 4.8 blockers

- packages/app/main/package.json
- packages/app/main/scripts/config/resources/entitlements.plist
This PR adds entitlements and updated AppID. The Devops pipeline has been updated to produce a signed and notarized installer.
Fixes #2120
> Feat: Added entitlements file to support Notarization

- README.md
Removing the **Click here** text for accessibility and clarity. Not everyone is clicking on the screen.
> Removing click here

- CHANGELOG.md
- packages/app/main/src/server/restServer.spec.ts
- packages/app/main/src/server/restServer.ts
> Added a log panel entry that displays the bot endpoint.

- CHANGELOG.md
- azure-pipelines-static-analysis.yml
This addresses one of the SDL compliance requirements: 
**Run SDL code analysis tools and automatically file bugs for identified security issues**
https://msazure.visualstudio.com/b32aa71e-8ed2-41b2-9d77-5bc261222004/_workitems/edit/7311219
===
Followed the same pattern as Composer: https://github.com/microsoft/BotFramework-Composer/blob/main/azure-pipelines-static-analysis.yml
> Added configuration for a nightly static code analysis pipeline

- CHANGELOG.md
- packages/app/main/package.json
- bumped app version to `4.13.0`
- prepped changelog
> Prepped 4.13.0 release

- packages/app/client/src/ui/editor/emulator/parts/log/log.scss
If the user applies large text and activity update section content information does not visible properly, so it would be difficult for the user to understand content information.
After applying large text, the Activity Update section content information does not visible properly and because of this, the user is unable to understand content information.
After applying large text, the Activity Update section content information should be visible properly, so those users get proper information.
3. Navigate on the welcome screen and select the Open Bot button.
4. Open A bot Dialog opens, navigate on the dialog and …
> [Accessibility] [Supporting Platform] Fix large text to be displayed properly in the Log panel

- .eslintrc.js
- packages/app/client/package.json
- packages/app/main/package.json
- packages/app/shared/package.json
- packages/extensions/json/package.json
- packages/extensions/luis/client/package.json
- packages/extensions/luis/package.json
- packages/extensions/qnamaker/client/package.json
- packages/extensions/qnamaker/package.json
- packages/sdk/client/package.json
- packages/sdk/shared/package.json
- packages/sdk/ui-react/package.json
- packages/tools/package.json
Resolves https://github.com/microsoft/BotFramework-Emulator/issues/2315
> Adds eslint-plugin-security

- packages/app/client/src/index.html
- packages/app/client/src/splash.html
- packages/app/client/src/ui/editor/emulator/parts/log/log.scss
- packages/app/client/src/ui/editor/emulator/parts/log/log.scss.d.ts
- packages/app/client/src/ui/editor/emulator/parts/log/log.tsx
- packages/app/client/src/ui/editor/emulator/parts/log/logEntry.tsx
- packages/app/client/src/ui/shell/explorer/servicePane/servicePane.tsx
- packages/app/client/src/ui/shell/mdi/tab/ngrokTab.tsx
- packages/app/client/src/ui/shell/mdi/tab/tab.tsx
- packages/app/client/src/ui/shell/mdi/tab/tabContainer.ts
- packages/app/client/src/ui/shell/mdi/tabBar/tabBar.tsx
- packages/app/client/src/ui/shell/mdi/tabbedDocument/contentWrapper/contentWrapper.tsx
Fixed issues found by Accessibility insights pass
> a11y: fix accessibility insights pass issues

- package-lock.json
- packages/app/client/package.json
- packages/app/main/package.json
- packages/app/main/src/server/routes/handlers/botFrameworkAuthentication.ts
- packages/app/shared/package.json
- packages/extensions/json/package.json
- packages/extensions/luis/client/package.json
- packages/extensions/qnamaker/client/package.json
- packages/sdk/client/package.json
- packages/sdk/shared/package.json
- packages/sdk/ui-react/package.json
Fixed missing types and the import for the `jsonwebtoken package`.
Also included a minor typescript upgrade into the PR.
> fix: jsonwebtoken usage

- CONTRIBUTING.md
- ThirdPartyNotices.txt
- packages/app/client/src/utils/eventHandlers.spec.ts
This holds minimal updates required to contributing guide after Electron upgrade work and other package updates.
Fixes #2453
> Update contributing guide
